### ISSUE TITLE
val_check_interval that accepts a timedelta

### ISSUE THREAD

**Issue by thecooltechguy** [Lightning-AI/lightning#9463] opened 2021-09-12 02:28 UTC
## 🚀 Feature

It would be really helpful if `val_check_interval` could also be configured with a `timedelta`, so that we can tell the job to run the validation epoch every N hours, for example.

### Motivation

Currently, some of the other training configurations within Lightning already support `timedelta`s, such as max training time, model checkpointing with some time interval during training, etc. Furthermore, when running a long training job, it would be very helpful if we can just specify to run the validation epoch every N hours, instead of every N steps.

### Pitch

Add support for Trainer's `val_check_interval` parameter to also accept a `timedelta` string (like `00:30:00`, which would represent that the val epoch should be run every 30 mins).

### Alternatives

Currently, we just estimate the number of steps that it would take for our desired `timedelta`, before a validation epoch is run.

**Comment by carmocca** [comment] 2022-07-19 17:57
Closing as a duplicate of https://github.com/Lightning-AI/lightning/issues/13324 which has more discussion

**Closed by carmocca** 2022-07-19 17:57 UTC
Labels: feature, help wanted
