### ISSUE TITLE
convert to onnx forward takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by guitar9** [Lightning-AI/lightning#15134] opened 2022-10-13 20:46 UTC
### Bug description

I get the error "forward takes 2 positional arguments but 3 were given" when I want to convert the trained classifier checkpoint to onnx. I used this train script to train the classifier: https://github.com/karasawatakumi/pytorch-image-classification/blob/main/train.py

I called the script with this paramters:
`python train.py -d mydataset -b 93 --img-size 256 -e 50 --model-name resnet50 --gpu-ids 0
`
This is my code for loading and converting the checkpoint to onnx (I coppied almost everything from train script, except the end where I am loading the checkpoint and save it to onnx)

```
import argparse
import os
from pprint import pprint

import timm
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image
from PIL import ImageFile

from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from pytorch_lightning.callbacks import LearningRateMonitor, ModelCheckpoint
from pytorch_lightning.utilities.seed import seed_everything
from torch.utils.data import DataLoader
from torchmetrics import Accuracy
from torchvision.datasets import ImageFolder

# solver settings
OPT = 'adam'  # adam, sgd
WEIGHT_DECAY = 0.0001
MOMENTUM = 0.9  # only when OPT is sgd
BASE_LR = 0.001
LR_SCHEDULER = 'step'  # step, multistep, reduce_on_plateau
LR_DECAY_RATE = 0.1
LR_STEP_SIZE = 5  # only when LR_SCHEDULER is step
LR_STEP_MILESTONES = [10, 15]  # only when LR_SCHEDULER is multistep


def get_optimizer(parameters) -> torch.optim.Optimizer:
    if OPT == 'adam':
        optimizer = torch.optim.Adam(parameters, lr=BASE_LR, weight_decay=WEIGHT_DECAY)
    elif OPT == 'sgd':
        optimizer = torch.optim.SGD(
            parameters, lr=BASE_LR, weight_decay=WEIGHT_DECAY, momentum=MOMENTUM
        )
    else:
        raise NotImplementedError()

    return optimizer

def get_lr_scheduler_config(optimizer: torch.optim.Optimizer) -> dict:
    if LR_SCHEDULER == 'step':
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer, step_size=LR_STEP_SIZE, gamma=LR_DECAY_RATE
        )
        lr_scheduler_config = {
            'scheduler': scheduler,
            'interval': 'epoch',
            'frequency': 1,
        }
    elif LR_SCHEDULER == 'multistep':
        scheduler = torch.optim.lr_scheduler.MultiStepLR(
            optimizer, milestones=LR_STEP_MILESTONES, gamma=LR_DECAY_RATE
        )
        lr_scheduler_config = {
            'scheduler': scheduler,
            'interval': 'epoch',
            'frequency': 1,
        }
    elif LR_SCHEDULER == 'reduce_on_plateau':
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='max', factor=0.1, patience=10, threshold=0.0001
        )
        lr_scheduler_config = {
            'scheduler': scheduler,
            'monitor': 'val/loss',
            'interval': 'epoch',
            'frequency': 1,
        }
    else:
        raise NotImplementedError

    return lr_scheduler_config

class SimpleModel(LightningModule):
    def __init__(
        self,
        model_name: str = 'resnet18',
        pretrained: bool = False,
        num_classes = None,
    ):
        super().__init__()
        self.save_hyperparameters()
        self.model = timm.create_model(
            model_name=model_name, pretrained=pretrained, num_classes=num_classes
        )
        self.train_loss = nn.CrossEntropyLoss()
        self.train_acc = Accuracy()
        self.val_loss = nn.CrossEntropyLoss()
        self.val_acc = Accuracy()

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        x, target = batch

        out = self(x)
        _, pred = out.max(1)
        print(out)

        loss = self.train_loss(out, target)
        acc = self.train_acc(pred, target)
        #self.log_dict({'train/loss': loss, 'train/acc': acc}, prog_bar=True)

        return loss

    def validation_step(self, batch, batch_idx):
        x, target = batch

        out = self(x)
        _, pred = out.max(1)

        loss = self.val_loss(out, target)
        acc = self.val_acc(pred, target)
        self.log_dict({'val/loss': loss, 'val/acc': acc})

    def configure_optimizers(self):
        optimizer = get_optimizer(self.parameters())
        lr_scheduler_config = get_lr_scheduler_config(optimizer)
        return {"optimizer": optimizer, "lr_scheduler": lr_scheduler_config}

model = SimpleModel(
    model_name="resnet50", pretrained=True, num_classes=136
)


CHECKPOINT_PATH = "XXX"
checkpoint = torch.load(CHECKPOINT_PATH)
model.load_state_dict(checkpoint['state_dict'])
torch_out = torch.onnx.export(model,             # model being run
                                (256,256),          # model input (or a tuple for multiple inputs)
                                "mymodel.onnx",      # where to save the model (can be a file or file-like object)
                                export_params=True,       # store the trained parameter weights inside the model file
                                verbose=True,
                                input_names=['main_input'],     # specify the name of input layer in onnx model
                                output_names=['main_output'])     # specify the name of input layer in onnx model
```

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by awaelchli** [comment] 2022-11-04 22:32
Hi @guitar9 
Did @lantiga's answer help you?

Here again a full example to illustrate how the "example input" works:

```py
import torch


class ModelWithOneInput(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(16 * 16, 2)

    def forward(self, input1):
        # input: (batch, height, width)
        return self.linear(input1.flatten(1))


inputs = (torch.rand(1, 16, 16), )
torch.onnx.export(ModelWithOneInput(), inputs, "one-input.onnx")


class ModelWithTwoInputs(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(16 * 16, 2)

    def forward(self, input1, input2):
        # input1: (batch, height, width)
        # input2: (batch, 2)
        return self.linear(input1.flatten(1)) * input2


inputs = (torch.rand(1, 16, 16), torch.rand(1, 2))
torch.onnx.export(ModelWithTwoInputs(), inputs, "two-inputs.onnx")

```

Finally, one cool thing about Lightning is that it has a `.to_onnx()` method. What's great is that you can define an `self.example_input_array` directly in your model definition. This means when you call` model.to_onnx("path/...")` you don't have to remember what the input shapes of your model are. I hope you will find it convenient. 

```py
from lightning.pytorch import LightningModule


class LightningModuleWithTwoInputs(LightningModule):

    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(16 * 16, 2)
        self.example_input_array = (torch.rand(1, 16, 16), torch.rand(1, 2))  # <----- here

    def forward(self, input1, input2):
        # input1: (batch, height, width)
        # input2: (batch, 2)
        return self.linear(input1.flatten(1)) * input2


model = LightningModuleWithTwoInputs()
model.to_onnx("lightning-module.onnx")   # <----- here

```
[More in our documentation.](https://pytorch-lightning.readthedocs.io/en/stable/deploy/production_advanced.html#compile-your-model-to-onnx)

I'm closing the ticket now as I am confident the issue is not with Lightning, rather a confusion on the input definitions required by onnx.

**Closed by awaelchli** 2022-11-04 22:32 UTC
Labels: needs triage
