### ISSUE TITLE
[PyTorch 2.0] Bug with `torch.compile()` and `self.log()`

### ISSUE THREAD

**Issue by mayeroa** [Lightning-AI/lightning#17177] opened 2023-03-23 10:33 UTC
### Bug description

When using brand new `torch.compile` from PyTorch 2.0 with Lightning 2.0, I encounter a weird error with my LightningModule...
The is running when no call to `self.log(...)` is made. When I try to log my loss value, the code crashes.

### How to reproduce the bug

```python
import lightning as L
import torch
import torch._dynamo
import torchvision
from timm import create_model
from torch import nn
from torch.utils.data import DataLoader
from torchvision import transforms


class CIFAR10DataModule(L.LightningDataModule):
    def __init__(self, batch_size=32) -> None:
        super().__init__()
        self.transform = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
        )

        self.batch_size = batch_size

        self.train_set = torchvision.datasets.CIFAR10(
            root='~/data', train=True, download=True, transform=self.transform
        )
        self.test_set = torchvision.datasets.CIFAR10(
            root='~/data', train=False, download=True, transform=self.transform
        )

    def train_dataloader(self):
        return DataLoader(self.train_set, batch_size=self.batch_size, shuffle=True, num_workers=4)

    def val_dataloader(self):
        return DataLoader(self.train_set, batch_size=self.batch_size, shuffle=False, num_workers=4)


class LitModel(L.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = create_model('resnet18', num_classes=10)
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, x):
        return self.model(x)

    def common_step(self, x, y, stage):
        logits = self(x)
        loss = self.criterion(logits, y)
        self.log(f'{stage}_loss', loss, on_epoch=True, prog_bar=True, logger=True)
        return loss

    def training_step(self, batch, batch_idx):
        x, y = batch
        loss = self.common_step(x, y, 'train')
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        loss = self.common_step(x, y, 'val')
        return {'val_loss': loss}

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters(), lr=0.001)


def main():
    datamodule = CIFAR10DataModule()
    model = LitModel()
    compiled_model = torch.compile(model)
    trainer = L.Trainer(max_epochs=3, devices='auto')
    trainer.fit(compiled_model, datamodule=datamodule)


if __name__ == '__main__':
    main()
```

### Error messages and logs

```
Files already downloaded and verified
Files already downloaded and verified
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA RTX A5000 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type             | Params
-----------------------------------------------
0 | model     | ResNet           | 11.2 M
1 | criterion | CrossEntropyLoss | 0     
-----------------------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.727    Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                                                                   | 0/2 [00:00<?, ?it/s]/alex/lib/python3.8/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
Traceback (most recent call last):
  File "test_3.py", line 72, in <module>
    main()
  File "test_3.py", line 68, in main
    trainer.fit(compiled_model, datamodule=datamodule)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1005, in _run_sanity_check
    val_loop.run()
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/loops/utilities.py", line 174, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/strategies/strategy.py", line 378, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "test_3.py", line 56, in validation_step
    loss = self.common_step(x, y, 'val')
  File "test_3.py", line 44, in common_step
    logits = self(x)
  File "test_3.py", line 46, in <graph break in common_step>
    self.log(f'{stage}_loss', loss, on_epoch=True, prog_bar=True, logger=True)
  File "/alex/lib/python3.8/site-packages/lightning/pytorch/core/module.py", line 403, in log
    apply_to_collection(value, dict, self.__check_not_nested, name)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 378, in wrapper
    resume_call_insts = self.create_call_resume_at(self.next_instruction)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1755, in create_call_resume_at
    new_code: types.CodeType = ContinueExecutionCache.lookup(
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/resume_execution.py", line 154, in lookup
    cls.cache[code][key] = cls.generate(code, lineno, *key)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/resume_execution.py", line 233, in generate
    new_code = transform_code_object(code, update)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 446, in transform_code_object
    return clean_and_assemble_instructions(instructions, keys, code_options)[1]
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 470, in clean_and_assemble_instructions
    code_options["co_stacksize"] = stacksize_analysis(instructions)
  File "/alex/lib/python3.8/site-packages/torch/_dynamo/bytecode_analysis.py", line 184, in stacksize_analysis
    assert fixed_point.value, "failed to reach fixed point"
AssertionError: failed to reach fixed point

from user code:
   File "/alex/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 94, in apply_to_collection
    if is_dataclass_instance(data):

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- PyTorch Version (e.g., 2.0): 2.0.0
#- Python version (e.g., 3.9): 3.8.13
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version:  11.7
#- How you installed Lightning(`conda`, `pip`, source): pip
```

</details>

### More info

The error appears when the following line is set:

```python
        self.log(f'{stage}_loss', loss, on_epoch=True, prog_bar=True, logger=True)
```

Without that line, the code is working as expected. Any idea?

cc @carmocca @tchaton

**Comment by BenedictusAryo** [comment] 2023-03-23 12:26
I think torch.compile supposed to be applied to nn.Module instead of L.LightningModule
try change:
```python
def main():
    datamodule = CIFAR10DataModule()
    model = LitModel()
    compiled_model = torch.compile(model)
    trainer = L.Trainer(max_epochs=3, devices='auto')
    trainer.fit(compiled_model, datamodule=datamodule)
```
to: 
```python
def main():
    datamodule = CIFAR10DataModule()
    model = LitModel()
    model.model = torch.compile(model.model)
    trainer = L.Trainer(max_epochs=3, devices='auto')
    trainer.fit(compiled_model, datamodule=datamodule)
```
or just put the torch.compile inside the LightningModule __init__ method:
```python
class LitModel(L.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torch.compile(create_model('resnet18', num_classes=10))
        self.criterion = nn.CrossEntropyLoss()
```

**Comment by mayeroa** [comment] 2023-03-24 08:46
@BenedictusAryo Thanks for your answer. Indeed, using `torch.compile` directly on the `nn.Module` will work, but as a user, I expect it to work also on a `LightningModule` (since, under the hood, it is a subclass of `nn.Module`.

Moreover, it is said in the changelog:

> 
> Lightning 2.0 is best friends with PyTorch 2.0. You can torch.compile your LightningModules now!
> 
> ```python
> import torch
> import lightning as L
> 
> model = LitModel()
> # This will compile forward and {training,validation,test,predict}_step 
> compiled_model = torch.compile(model)
> 
> trainer = L.Trainer()
> trainer.fit(compiled_model)
> ```

So we should expect `torch.compile` working with our LightningModules too. :)
Thanks for the workaround in the meantime.

**Comment by carmocca** [comment] 2023-03-28 16:34
I'm not able to reproduce. Can you share the output of `pip list`?

**Comment by carmocca** [comment] 2023-03-28 18:11
I was able to trim the issue down and opened a bug report in https://github.com/pytorch/pytorch/issues/97811

I believe this is only an issue on Python 3.8

**Comment by mayeroa** [comment] 2023-03-28 18:28
Thanks @carmocca for your help. Indeed, I should have made it clearer that the 3.8 version of python was used. I haven't tested other versions. 
Thanks for your investigation. 😊

**Comment by euirim** [comment] 2023-04-12 23:40
> I think torch.compile supposed to be applied to nn.Module instead of L.LightningModule try change:
> 
> ```python
> def main():
>     datamodule = CIFAR10DataModule()
>     model = LitModel()
>     compiled_model = torch.compile(model)
>     trainer = L.Trainer(max_epochs=3, devices='auto')
>     trainer.fit(compiled_model, datamodule=datamodule)
> ```
> 
> to:
> 
> ```python
> def main():
>     datamodule = CIFAR10DataModule()
>     model = LitModel()
>     model.model = torch.compile(model.model)
>     trainer = L.Trainer(max_epochs=3, devices='auto')
>     trainer.fit(compiled_model, datamodule=datamodule)
> ```
> 
> or just put the torch.compile inside the LightningModule **init** method:
> 
> ```python
> class LitModel(L.LightningModule):
>     def __init__(self):
>         super().__init__()
>         self.model = torch.compile(create_model('resnet18', num_classes=10))
>         self.criterion = nn.CrossEntropyLoss()
> ```

Just an FYI; I think if you only compile the `nn.Module` within a `LightningModule`, lightning's `load_from_checkpoint` no longer works because the keys in the state_dict have been renamed: i.e. from `torch_model.decoder.embed.weight` to `torch_model._orig_mod.decoder.embed.weight`, causing missing and unexpected key errors when trying to load from checkpoint.

**Comment by lkhphuc** [comment] 2023-08-04 12:27
On Lightning 2.0.6 or nightly with Pytorch nightly (2023-08-03), I now have a different error:
```
Traceback (most recent call last):
  File "/home/plekhac/crocoman-toy/tmp2.py", line 72, in <module>
    main()
  File "/home/plekhac/crocoman-toy/tmp2.py", line 68, in main
    trainer.fit(compiled_model, datamodule=datamodule)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 540, in fit
    call._call_and_handle_interrupt(
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 985, in _run
    results = self._run_stage()
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1026, in _run_stage
    self._run_sanity_check()
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1055, in _run_sanity_check
    val_loop.run()
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 147, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 401, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 307, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 388, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
  File "/home/plekhac/crocoman-toy/tmp2.py", line 56, in validation_step
    loss = self.common_step(x, y, 'val')
  File "/home/plekhac/crocoman-toy/tmp2.py", line 46, in common_step
    self.log(f'{stage}_loss', loss, on_epoch=True, prog_bar=True, logger=True)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 398, in log
    apply_to_collection(value, dict, self.__check_not_nested, name)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 399, in <resume in log>
    apply_to_collection(
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 445, in <resume in log>
    results.reset(metrics=False, fx=self._current_fx_name)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 486, in <resume in log>
    results.log(
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 387, in log
    meta.sync = _Sync(_should=sync_dist, fn=sync_dist_fn, _group=sync_dist_group, rank_zero_only=rank_zero_only)
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 395, in <resume in log>
    raise MisconfigurationException(
  File "/nfs/tools/3d/caiman/conda/envs/caiman-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 395, in <resume in log>
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You called `self.log(val_loss, ...)` twice in `validation_step` with different arguments. This is not allowed
```
This is the same for both my own model and the snippet above.

**Comment by carmocca** [comment] 2023-08-04 18:31
Closing, this was fixed in PyTorch

**Closed by carmocca** 2023-08-04 18:31 UTC
Labels: bug, 3rd party, torch.compile, ver: 2.0.x
