### ISSUE TITLE
Add the compilation of the model as an option in the CLI

### ISSUE THREAD

**Issue by rcremese** [Lightning-AI/lightning#17692] opened 2023-05-25 11:05 UTC
### Description & Motivation

I'm using a lot pytorch lightning for my DL projects and love how it speeds up my  experiments.
I also love the pre-made CLI that avoid a lot of pain and cleans up the experiment process.
I just wonder when the model compilation allowed by the PyTorch V2 update will be included in the CLI.
 

### Pitch

Add a `--compile` flag to the lightning CLI to allow users with PyTorch >= 2.0 to compile the models they want to work on. 

### Alternatives

Overwrite the LightningCLI to call the `torch.compile()` function on a created model

cc @borda @tchaton @justusschock @awaelchli @carmocca @mauvilsa

**Comment by yzx9** [comment] 2023-05-25 15:37
Looks like a duplicate of #17283

**Comment by carmocca** [comment] 2023-05-25 15:56
Oh right. I forgot about that one. Closing this one then, sorry @rcremese!

**Closed by carmocca** 2023-05-25 15:56 UTC
Labels: feature, design, lightningcli, pl
