### ISSUE TITLE
Allow user to set lr_scheduler interval=step through LightningCLI

### ISSUE THREAD

**Issue by mouroutzoglou** [Lightning-AI/lightning#15340] opened 2022-10-26 16:45 UTC
## 🚀 Feature

I'd like to be able to set the lr_scheduler interval=step through cli or yaml config.

### Motivation

Having to set this parameter in the model configure_optimizers function beats the purpose of having modular config files.

cc @borda @carmocca @mauvilsa

**Comment by rusmux** [comment] 2023-02-16 16:38
@carmocca Any updates on this?

**Comment by mauvilsa** [comment] 2023-02-16 17:00
@rusmux you could add a `lr_scheduler_config: dict` parameter to your `LightningModule.__init__`. And implement `configure_optimizers` such that it uses it. Combined with https://pytorch-lightning.readthedocs.io/en/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers you can have any optimizer and scheduler.

If this is too complicated, you can propose some ideas to support this in a simpler way.

**Comment by rusmux** [comment] 2023-02-16 20:46
This is exactly what I was doing, but I decided to remove the custom logic from `configure_optimizers` because that way you won't be able to change it from the CLI. And changing the configuration file every time is a bit tedious. Why not just add the `interval` argument, as the `monitor` argument is added to `pytorch_lightning.cli.ReduceLROnPlateau`?

**Comment by mauvilsa** [comment] 2023-02-17 03:07
> This is exactly what I was doing, but I decided to remove the custom logic from `configure_optimizers` because that way you won't be able to change it from the CLI.

Note that what I proposed makes everything becomes configurable via command line and config files. So I guess that what you did is not the same.

**Comment by rusmux** [comment] 2023-02-17 07:46
Well, I am not sure I did everything correctly, but here is what I tried:

Module:

<img width="469" alt="Screenshot 86" src="https://user-images.githubusercontent.com/85135806/219581130-4c81a625-99ac-443e-8dbf-51ede992e03a.png">

<img width="823" alt="Screenshot 87" src="https://user-images.githubusercontent.com/85135806/219581256-c304d586-eb7c-4520-b9fb-52a19fb4ccac.png">

Config:

<img width="465" alt="Screenshot 88" src="https://user-images.githubusercontent.com/85135806/219581374-bcb718e7-d06e-44e9-b038-fb958aa63298.png">

Now, when I try to change the learning rate via CLI, I end up with this:

If I use `--model.optimizer_init.init_args.lr=0.123`:

<img width="343" alt="Screenshot 89" src="https://user-images.githubusercontent.com/85135806/219581830-d66af2ea-a8ed-4185-9dfe-07d939080624.png">

If `--model.optimizer_init.lr=0.123`:

<img width="296" alt="Screenshot 90" src="https://user-images.githubusercontent.com/85135806/219581928-a3c5f224-5308-4c09-b07e-62bf4bddde15.png">

In both of these cases, it just adds a new entry to the configuration, but does not change the learning rate.

**Comment by mauvilsa** [comment] 2023-02-17 12:16
The downside of using `dict` as a type is that anything is accepted. The parser is unable to validate with specific types. If the user implements things incorrectly or gives a wrong value, cryptic error messages are obtained. This might be your problem.

The link that I sent before describes how to do this with dependency injection, which avoids the previously mentioned issues for the optimizer and scheduler. A similar comment goes for `model_init: dict`, that is not recommended. The `lightning_args` you have, is more or less what I suggested. Though the `dict` downsides also apply, but less problematic. If you only want to make configurable `interval`, then better to only expose that one with its specific type.

My suggestion is something like (not tested):

```python
class Module(pl.LightningModule):
    def __init__(
        self,
        optimizer: pl.cli.OptimizerCallable = torch.optim.Adam,
        scheduler: pl.cli.LRSchedulerCallable = torch.optim.lr_scheduler.ReduceLROnPlateau,
        scheduler_config: Optional[dict] = None,
    ):
        super().__init__()
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.scheduler_config = scheduler_config or {}

    def configure_optimizers(self):
        optimizer = self.optimizer(self.parameters())
        scheduler = self.scheduler(optimizer)
        return (
            [optimizer],
            [{"scheduler": scheduler, **self.scheduler_config}],
        )
```

**Comment by rusmux** [comment] 2023-02-17 14:17
I see, thank you for the explanation! However, when I try to run my code this way, I get an error:

```
...
File "/opt/homebrew/Caskroom/mambaforge/base/envs/compress-models/lib/python3.10/site-packages/jsonargparse/core.py", line 720, in dump
    self.check_config(cfg)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/compress-models/lib/python3.10/site-packages/jsonargparse/core.py", line 1090, in check_config
    raise type(ex)(message) from ex
TypeError: Configuration check failed :: Key "params" is required but not included in config object or its value is None.
```

My minimal code:

```Python
class Module(pl.LightningModule):

    def __init__(
        self,
        model: Callable,
        optimizer: pl.cli.OptimizerCallable,
    ) -> None:
        super().__init__()
        self.model = model
        self.optimizer = optimizer

    def configure_optimizers(self) -> Any:
        return self.optimizer(self.model.parameters())

cli = LightningCLI(
        Module,
        TinyImageNetDataModule,
        args=args,
        parser_kwargs={"parser_mode": "omegaconf", "default_config_files": ["configs/base.yaml"]},
        auto_configure_optimizers=False,
        run=False,
    )

cli.trainer.fit(cli.model, cli.datamodule)
```

My config:

```Yaml
model:

  model:
    class_path: src.model.models.ResNet50
    init_args:
      num_classes: ${num_classes}

  optimizer:
    class_path: torch.optim.Adam
```

I followed you example and the documentation, but still there is an error about the optimizer `params` argument. I can't figure out how to solve this

**Comment by mauvilsa** [comment] 2023-02-17 16:10
Did you change the type of `model` to `Callable` based on what I said? That wasn't what I meant. The type should be `nn.Module` or a more specific subclass. The case of optimizer is special because it is impossible to instantiate before the module exists.

That code above does not make sense. If model is a callable, then `self.model.parameters()` would fail because in general a function would not have an `parameters` attribute. With what is specified in the config, I would have expected that also to fail. But you mention some other error. I don't know what is the issue.

I am currently traveling and can't test any code. Maybe run setting the environment variable `JSONARGPARSE_DEBUG=true` to get more information.

**Comment by rusmux** [comment] 2023-02-17 20:51
As I checked, the problem is not in the `model`. The type `Callable` is just more generic form of typing, I set it temporarily. I checked, that it has the `parameters` attribute. At last, I removed all the logic from the "Module", but still got the same error. I think I'll leave it as it is for now, but thank you for all the explanations!

**Comment by rusmux** [comment] 2023-02-17 23:34
After experimenting, I realized that all my `model_init`, `criterion_init` were redundant and LightningCLI managed them for me. However, I still could not instantiate optimizer and scheduler from the config file, if I changed `optimizer_init` to `optimizer`. Also, in the documentation, there is a remark: 

<img width="783" alt="Screenshot 102" src="https://user-images.githubusercontent.com/85135806/219816559-8b08558c-a911-4860-8025-000e78e332d7.png">

Maybe it has something to do with it.

**Comment by mauvilsa** [comment] 2023-02-21 23:00
The `Key "params" is required but not included ...` error is a bug. You can avoid it by instantiating `LightningCLI` with `save_config_callback=None`. Unfortunately this means that the automatic save of config is broken when using `OptimizerCallable`. I will fix this as soon as possible. I think the problem is in jsonargparse, not in lightning.

**Comment by mauvilsa** [comment] 2023-02-22 00:55
Created a pull request that should fix the issue, see https://github.com/omni-us/jsonargparse/pull/246. @rusmux you can try it out by installing jsonargparse as:

```bash
pip install "jsonargparse[signatures] @ https://github.com/omni-us/jsonargparse/zipball/fix-partial-callable-instance"
```

**Comment by rusmux** [comment] 2023-02-22 07:44
Thank you! Now it's working correctly.

**Comment by tommycwh** [comment] 2023-03-30 02:59
> Created a pull request that should fix the issue, see [omni-us/jsonargparse#246](https://github.com/omni-us/jsonargparse/pull/246). @rusmux you can try it out by installing jsonargparse as:
> 
> ```shell
> pip install "jsonargparse[signatures] @ https://github.com/omni-us/jsonargparse/zipball/fix-partial-callable-instance"
> ```

I got the same error ```TypeError: Configuration check failed :: Key "params" is required but not included in config object or its value is None.```. I tried to re-install jsonargparse using the given link, but it seems that the link does not work now.

```ERROR: HTTP error 404 while getting https://github.com/omni-us/jsonargparse/zipball/fix-partial-callable-instance```

I guess I am using a newer version of jsonargparse. If I want to revert to version which solves the ```Key "params" is required``` here, which version should I use?

-----
My environment:
```
python                       3.8

torch                          2.0.0+cu118
pytorch-lightning        2.0.0  
lightning                    2.0.0  
jsonargparse             4.20.0 
```

My ```BoringModel```
```
import torch
import torch.nn as nn
import lightning as L
from lightning.pytorch.cli import OptimizerCallable, LRSchedulerCallable

class BoringModel(L.LightningModule) :
    def __init__(self, 
                 optimizer: OptimizerCallable = torch.optim.Adam,
                 scheduler: LRSchedulerCallable = torch.optim.lr_scheduler.ConstantLR,
                 optimizer_kwargs: dict = {},
                 scheduler_kwargs: dict = {},
                 **kwargs,
                 ):
        super().__init__()
        self.save_hyperparameters()

        self.model = nn.Linear(3,32)
        self.optimizer = optimizer
        self.optimizer_kwargs = optimizer_kwargs        
        self.scheduler = scheduler
        self.scheduler_kwargs = scheduler_kwargs

    def configure_optimizers(self):
        # https://github.com/Lightning-AI/lightning/issues/15340#issuecomment-1434560283
        optimizer = self.optimizer(params=self.model.parameters(), **self.optimizer_kwargs)
        scheduler = self.scheduler(optimizer=optimizer, **self.scheduler_kwargs)
        return {"optimizer": optimizer, "lr_scheduler": scheduler}

    def forward(self, x):
        pass
    
    def training_step(self, batch, batch_idx):
        pass

    def validation_step(self, batch, batch_idx):
        pass


    def test_step(self, batch, batch_idx):
        pass
```

My ```main.py```
```
# main.py
from lightning.pytorch.cli import LightningCLI
import lightning as L

def cli_main():
    # note: don't call fit!!
    cli = LightningCLI(L.LightningModule, L.LightningDataModule, 
                       subclass_mode_model=True, subclass_mode_data=True,)

if __name__ == "__main__":
    cli_main()
```

My config file ```boring_model.yaml```
```
model:
  class_path: boring_model.BoringModel
  init_args:
    optimizer: 
      class_path: torch.optim.Adam
    optimizer_kwargs:
      lr: 0.01
    scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR

data:
  class_path: lightning.pytorch.demos.boring_classes.BoringDataModule

trainer:
  accelerator: auto
```

My command to start the trainer
```
python3 main.py fit --config boring_model.yaml
```

**Comment by mauvilsa** [comment] 2023-03-30 04:59
> I tried to re-install jsonargparse using the given link, but it seems that the link does not work now.

That pull request was merged, therefore it is in the master branch. Anyway, just now I created a released, so the fix is in jsonargparse v4.20.1.

**Comment by tommycwh** [comment] 2023-03-30 15:19
I see. I see how one can configure the optimizer/scheduler by setting the arguments through a command on the CLI, but how could I set the config .yaml file if I want to do this through the config file? I tried the followings but none of these work.

(1) optimizer/scheduler under model.init_args
config file:
```
model:
  class_path: boring_model.BoringModel
  init_args:
    optimizer: 
      class_path: torch.optim.Adam
      init_kwargs:
        lr: 0.01
    scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR
```
error:
```
main.py [options] fit: error: Parser key "model":
  Problem with given class_path 'debug.boring_model.BoringModel':
    - Parser key "optimizer":
      Type typing.Callable[[typing.Iterable], torch.optim.optimizer.Optimizer] expects a function or a callable class: Dict must include a class_path and optionally init_args, but got {'class_path': 'torch.optim.Adam', 'init_kwargs': {'lr': 0.01}}. Got value: Namespace(class_path='torch.optim.Adam', init_kwargs={'lr': 0.01})
```

(2) optimizer/schduler under model
config file
```
model:
  class_path: debug.boring_model.BoringModel

  optimizer: 
    class_path: torch.optim.Adam
    init_kwargs:
      lr: 0.01
  scheduler:
    class_path: torch.optim.lr_scheduler.ConstantLR
```
error:
```
main.py [options] fit: error: Parser key "model":
  Not a valid LightningModule. Got value: {'class_path': 'debug.boring_model.BoringModel', 'optimizer': {'class_path': 'torch.optim.Adam', 'init_kwargs': {'lr': 0.01}}, 'scheduler': {'class_path': 'torch.optim.lr_scheduler.ConstantLR'}}
  Subclass types expect one of:
  - a class path (str)
  - a dict with class_path entry
  - a dict without class_path but with init_args entry (class path given previously)
```
(3) put optimizer/scheduler outside model
config file:
```
model:
  class_path: boring_model.BoringModel

optimizer: 
  class_path: torch.optim.Adam
  init_kwargs:
    lr: 0.01
```
error:
```
usage: main.py [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict} ...
main.py: error: 'Configuration check failed :: No action for destination key "optimizer.init_kwargs.lr" to check its value.'
```

**Comment by mauvilsa** [comment] 2023-03-30 15:39
The first config is correct except that it should be `init_args` instead of `init_kwargs`.

**Comment by tommycwh** [comment] 2023-03-31 02:58
Oh, it is a silly mistake. It works fine now. Thank you very much for your help.

As a reference, let me paste my code below.

My ```BoringModel```
```
class BoringModel(L.LightningModule) :
    def __init__(self, 
                 optimizer: OptimizerCallable = torch.optim.Adam,
                 scheduler: LRSchedulerCallable = torch.optim.lr_scheduler.ConstantLR,
                 **kwargs,
                 ):
        super().__init__()
        self.save_hyperparameters()

        self.model = nn.Linear(3,32)
        self.optimizer = optimizer
        self.scheduler = scheduler

    def configure_optimizers(self):
        optimizer = self.optimizer(self.parameters())
        scheduler = self.scheduler(optimizer)
        return {"optimizer": optimizer, "lr_scheduler": scheduler}
```
My config file
```
model:
  class_path: boring_model.BoringModel
  init_args:
    optimizer: 
      class_path: torch.optim.Adam
      init_args:
        lr: 0.01
    scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR

data:
  class_path: lightning.pytorch.demos.boring_classes.BoringDataModule

trainer:
  accelerator: auto
```
My ```main.py```
```
# main.py
from lightning.pytorch.cli import LightningCLI
import lightning as L

def cli_main():
    cli = LightningCLI(L.LightningModule, L.LightningDataModule, 
                       subclass_mode_model=True, subclass_mode_data=True,
                       auto_configure_optimizers=False)

if __name__ == "__main__":
    cli_main()
```
My command to start the trainer
```
python3 main.py fit \
--config boring_model.yaml
```

**Comment by tommycwh** [comment] 2023-03-31 05:26
Sorry, I have one more follow-up question. Based on the settings specified above, if I use ```save_hyperparameters()``` to log the model hyperparameters, it seems that only the type of the Callable objects are saved, but not the hyperparameter values. Is it possible to make  the ```save_hyperparameters()``` function to save the values from ```init_args``` in the config file, or could I get the ```init_args``` values inside a ```LightningModule``` so that I can log them in another way?

e.g., the hyperparameters shown on tensorboard.
![image](https://user-images.githubusercontent.com/25646584/229030694-25d9a3e6-1a93-45b9-a6c1-49d0ebb9ee02.png)

**Comment by mauvilsa** [comment] 2023-03-31 06:16
`save_hyperparameters` currently is not supported for `LightningCLI` with dependency injection. I have proposed how this could be done, but I have not worked on that yet, see https://github.com/Lightning-AI/lightning/issues/15427#issuecomment-1298869338.

You can subclass `SaveConfigCallback` so that it logs the config. This would be something like (not tested):

```python
class MySaveConfigCallback(SaveConfigCallback):
    def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        super().setup(trainer, pl_module, stage)
        if trainer.is_global_zero and not self.already_saved:
            # Log self.config using trainer.logger
```

Then provide `save_config_callback=MySaveConfigCallback` when instantiating `LightningCLI`.

**Comment by tommycwh** [comment] 2023-04-20 01:28
I tried to print out something under the if condition, but it seems that it is never executed. I guess this if condition is needed to make it only runs at the beginning? What should be the correct if condition?

Below are the code I used:

My ```SaveConfigCallback``` object
```
from lightning import LightningModule, Trainer
from lightning.pytorch.cli import SaveConfigCallback

class SaveConfigWithInitArgsCallback(SaveConfigCallback):
    def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        super().setup(trainer, pl_module, stage)
        
        if trainer.is_global_zero and not self.already_saved:
            print("===== SaveConfigWithInitArgsCallback =====")

            self.already_saved = True
``` 

My ```main.py```:
```
# main.py
from lightning.pytorch.cli import LightningCLI
import lightning as L

from utils.callbacks.logging import SaveConfigWithInitArgsCallback

def cli_main():
    cli = LightningCLI(L.LightningModule, L.LightningDataModule, 
                       subclass_mode_model=True, subclass_mode_data=True,
                       auto_configure_optimizers=False,
                       save_config_callback=SaveConfigWithInitArgsCallback)


if __name__ == "__main__":
    cli_main()
```

**Comment by mauvilsa** [comment] 2023-04-20 04:04
I think that the problem is that the `super` sets `already_saved` to `True`. Try changing the order, i.e.

```python
class MySaveConfigCallback(SaveConfigCallback):
    def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        if trainer.is_global_zero and not self.already_saved:
            # Log self.config using trainer.logger
            # Don't set self.already_saved = True since super will do it
        super().setup(trainer, pl_module, stage)
```

**Comment by tommycwh** [comment] 2023-04-20 05:06
Interestingly, the program freezes if I put the super().setup(...) line at last. I cannot tell whether it freezes in the setup() function or in some other function after setup() though.

For example, I print out these lines:
```
...
Log optimizer config.                               
Log scheduler config.
self.already_saved = True                           
super().setup(trainer, pl_module, stage)
```
using this:
```
class SaveConfigWithInitArgsCallback(SaveConfigCallback):
    def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        if trainer.is_global_zero and not self.already_saved:
            print("===== SaveConfigWithInitArgsCallback =====")

            # Get model config
            config = self.config.as_dict()
            print("config: ")
            print(config)
            model_config = config['model']['init_args']

            # Model
            if 'model' in model_config :
                print("Log model config.")
                model_init_args = model_config['model']['init_args']
                trainer.logger.log_hyperparams({'model': model_init_args})

            # Optimizer
            if 'optimizer' in model_config :
                print("Log optimizer config.")
                optimizer_init_args = model_config['optimizer']['init_args']
                trainer.logger.log_hyperparams({'optimizer': optimizer_init_args})

            # Scheduler
            if 'scheduler' in model_config :
                print("Log scheduler config.")
                scheduler_init_args = model_config['scheduler']['init_args']
                trainer.logger.log_hyperparams({'scheduler': scheduler_init_args})

            self.already_saved = True
            print("self.already_saved = True")

        print("super().setup(trainer, pl_module, stage)")
        super().setup(trainer, pl_module, stage)
```

The model does start training if I put the super().setup(...) line at first, but as I mentioned in the previous comment, the if condition is not executed.

**Comment by mauvilsa** [comment] 2023-04-21 05:17
I guess it freezes because a `trainer.strategy.broadcast` is missing. What is now clear to me is that subclassing `SaveConfigCallback` to save in a logger is not trivial. We should improve it so that it is really easy to do and document how to do it. I will make a proposal.

For now, maybe a safer bet is to simply copy the entire [`setup` from the parent class](https://github.com/Lightning-AI/lightning/blob/30322884bed27cd5f24cedd365c95ae90ee963c0/src/lightning/pytorch/cli.py#L227) and not call `super`. Then you custom save can be added after the [standard save](https://github.com/Lightning-AI/lightning/blob/30322884bed27cd5f24cedd365c95ae90ee963c0/src/lightning/pytorch/cli.py#L255).

**Comment by tommycwh** [comment] 2023-04-23 03:14
I made the setup  function like the following. It can save the hyperparameters inside dictionaries, but only some of them.

```
def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
    if self.already_saved:
        return

    log_dir = trainer.log_dir  # this broadcasts the directory
    assert log_dir is not None
    config_path = os.path.join(log_dir, self.config_filename)
    fs = get_filesystem(log_dir)

    if not self.overwrite:
        # check if the file exists on rank  
        file_exists = fs.isfile(config_path) if trainer.is_global_zero else False
        # broadcast whether to fail to all ranks
        file_exists = trainer.strategy.broadcast(file_exists)
        if file_exists:
            raise RuntimeError(
                f"{self.__class__.__name__} expected {config_path} to NOT exist. Aborting to avoid overwriting"
                " results of a previous run. You can delete the previous config file,"
                " set `LightningCLI(save_config_callback=None)` to disable config saving,"
                ' or set `LightningCLI(save_config_kwargs={"overwrite": True})` to overwrite the config file.'
            )

    # save the file on rank 0
    if trainer.is_global_zero:
        # save only on rank zero to avoid race conditions.
        # the `log_dir` needs to be created as we rely on the logger to do it usually
        # but it hasn't logged anything at this point
        fs.makedirs(log_dir, exist_ok=True)
        self.parser.save(
            self.config, config_path, skip_none=False, overwrite=self.overwrite, multifile=self.multifile
        )
        self.already_saved = True

        # Log kwargs in dicts
        # Get model config
        config = self.config.as_dict()
        print("config: ")
        print(config)
        model_config = config['model']['init_args']

        # Model
        if 'model' in model_config :
            print("Log model config.")
            model_init_args = model_config['model']['init_args']
            print(model_init_args)
            trainer.logger.log_hyperparams({'model': model_init_args})

        # Optimizer
        if 'optimizer' in model_config :
            print("Log optimizer config.")
            optimizer_init_args = model_config['optimizer']['init_args']
            print(optimizer_init_args)
            trainer.logger.log_hyperparams({'optimizer': optimizer_init_args})

        # Scheduler
        if 'scheduler' in model_config :
            print("Log scheduler config.")
            scheduler_init_args = model_config['scheduler']['init_args']
            print(scheduler_init_args)
            trainer.logger.log_hyperparams({'scheduler': scheduler_init_args})


    # broadcast so that all ranks are in sync on future calls to .setup()
    self.already_saved = trainer.strategy.broadcast(self.already_saved)
```

I am expecting it to save hyperparameters from 3 dictionaries: ```model```, ```optimizer``` and ```scheduler```.

![Screenshot from 2023-04-23 10-51-19](https://user-images.githubusercontent.com/25646584/233817091-ec9cecb5-282b-467a-9e1d-b44eaaa55ad9.png)


However, under the ```HPARAMS``` tag in the TensorBoard page, only the ```model``` hyperparameters are saved (I verified that the ```model``` hyperparameters are saved under my ```if 'model' in model_config``` condition, as when I commented this part out, no hyperparameter is saved. See the row ```versoin_3```)

![Screenshot from 2023-04-23 10-50-11](https://user-images.githubusercontent.com/25646584/233817221-ff1a336a-955e-4aaa-a794-d1d8dfc4091a.png)

--------
Later, I found that it does not work with multiple calls of ```trainer.logger.log_hyperparams()```. Calls subsequent to the first call do not work. The following ```setup()``` function is the one I found working. 

```
def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
    if self.already_saved:
        return

    log_dir = trainer.log_dir  # this broadcasts the directory
    assert log_dir is not None
    config_path = os.path.join(log_dir, self.config_filename)
    fs = get_filesystem(log_dir)

    if not self.overwrite:
        # check if the file exists on rank  
        file_exists = fs.isfile(config_path) if trainer.is_global_zero else False
        # broadcast whether to fail to all ranks
        file_exists = trainer.strategy.broadcast(file_exists)
        if file_exists:
            raise RuntimeError(
                f"{self.__class__.__name__} expected {config_path} to NOT exist. Aborting to avoid overwriting"
                " results of a previous run. You can delete the previous config file,"
                " set `LightningCLI(save_config_callback=None)` to disable config saving,"
                ' or set `LightningCLI(save_config_kwargs={"overwrite": True})` to overwrite the config file.'
            )

    # save the file on rank 0
    if trainer.is_global_zero:
        # save only on rank zero to avoid race conditions.
        # the `log_dir` needs to be created as we rely on the logger to do it usually
        # but it hasn't logged anything at this point
        fs.makedirs(log_dir, exist_ok=True)
        self.parser.save(
            self.config, config_path, skip_none=False, overwrite=self.overwrite, multifile=self.multifile
        )
        self.already_saved = True

        # Log kwargs in dicts
        # Get model config
        config = self.config.as_dict()
        print("config: ")
        print(config)
        model_config = config['model']['init_args']

        hparams_dict = {}
        # Model
        if 'model' in model_config :
            print("Log model config.")
            model_init_args = model_config['model']['init_args']
            print(model_init_args)
            # trainer.logger.log_hyperparams({'model': model_init_args})
            hparams_dict.update({'model': model_init_args})

        # Optimizer
        if 'optimizer' in model_config :
            print("Log optimizer config.")
            optimizer_init_args = model_config['optimizer']['init_args']
            print(optimizer_init_args)
            # trainer.logger.log_hyperparams({'optimizer': optimizer_init_args})
            hparams_dict.update({'optimizer': optimizer_init_args})


        # Scheduler
        if 'scheduler' in model_config :
            print("Log scheduler config.")
            scheduler_init_args = model_config['scheduler']['init_args']
            print(scheduler_init_args)
            # trainer.logger.log_hyperparams({'scheduler': scheduler_init_args})
            hparams_dict.update({'scheduler': scheduler_init_args})

        # Save all params at once
        if hparams_dict != {} :
            print("save hparams.")
            trainer.logger.log_hyperparams(hparams_dict)


    # broadcast so that all ranks are in sync on future calls to .setup()
    self.already_saved = trainer.strategy.broadcast(self.already_saved)
```
The TensorBoard page below shows my successful and unsuccessful trials 
(version_0: save all hparams at once; 
version_1: multiple calls of  ```trainer.logger.log_hyperparams()```,  ```optimizer``` hparams are not saved.)

![Screenshot from 2023-04-23 11-09-11](https://user-images.githubusercontent.com/25646584/233817664-fb1aceea-f701-479e-bc00-a68ec27eea0e.png)

@mauvilsa Thanks again for your help!

**Comment by mauvilsa** [comment] 2023-04-26 04:33
> I guess it freezes because a `trainer.strategy.broadcast` is missing. What is now clear to me is that subclassing `SaveConfigCallback` to save in a logger is not trivial. We should improve it so that it is really easy to do and document how to do it. I will make a proposal.

Created pull request https://github.com/Lightning-AI/lightning/pull/17475 with a proposal.

**Comment by mauvilsa** [comment] 2023-04-28 05:35
@tommycwh please do have a look at #17475 which would make this much easier.

**Comment by tommycwh** [comment] 2023-04-30 02:20
I am sorry that this is my first time trying to checkout a PR and I do not know how to do this. I tried to run ```gh pr checkout 17475``` and it says my local copy of ```lighting``` is up-to-date, but the code in ```src/lightning/pytorch/cli.py``` does not seems to reflect the changes mentioned in the PR. What should I do to get that updated?

**Comment by mauvilsa** [comment] 2023-05-01 08:51
I was just suggesting that you look at the pull request in the github website. For example look at the diff of the docs to see how it would be done if this feature is accepted https://github.com/Lightning-AI/lightning/pull/17475/files

**Comment by tommycwh** [comment] 2023-05-03 02:51
Sorry, I misunderstood your words. I think it is easier because we do not need to take care of the other things in the ```setup()``` function. 

However, I would want some more instructions on how to implement my ```save_config()``` function. For example, in my example above, there are some hyperparameters (like those numerical values) that can be saved by the "default" config saving mechanism and I would need to implement my own mechanism for the others that cannot be saved automaically (like the init_args). 

If I am implementing the ```save_config()``` function, could I reuse the existing "default" saving mechanism and just add my own functions to save the additional stuff, or should I write the functions to save everything?

**Comment by Laurent2916** [comment] 2023-08-09 15:25
Hi all !
Wouldn't it be possible to modify line 599 in the following file to use the [`lr_scheduler_config`](https://github.com/Lightning-AI/lightning/issues/15340#issuecomment-1433411205) ?

https://github.com/Lightning-AI/lightning/blob/efa7b2f9efd8d268a463b73e5d9154a6c5ab4831/src/lightning/pytorch/cli.py#L581-L601

**Comment by mauvilsa** [comment] 2023-08-10 06:26
This thread is way to long and I think we should close it. From what I understand, the issue has already been resolved. `interval=step` does not work with the CLI's automatic `configure_optimizers` and there is no point in changing it. Whoever wants some feature that the automatic `configure_optimizers` does not provide, they should use `auto_configure_optimizers=False` and do dependency injection as explained in [multiple-optimizers-and-schedulers](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers).

**Closed** 2023-08-10 09:27 UTC
Labels: feature, help wanted, lightningcli

**Comment by apple2373** [comment] 2024-09-12 05:05
I did the following way. 

```
class MyLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.add_argument("--lr_step_interval", default="epoch")

    # override this
    # https://github.com/Lightning-AI/pytorch-lightning/blob/f3f10d460338ca8b2901d5cd43456992131767ec/src/lightning/pytorch/cli.py#L605-L606
    def configure_optimizers(
        self,
        lightning_module: LightningModule,
        optimizer: Optimizer,
        lr_scheduler: Optional[LRSchedulerTypeUnion] = None,
    ) -> Any:
        if lr_scheduler is None:
            return optimizer
        if isinstance(lr_scheduler, ReduceLROnPlateau):
            return {
                "optimizer": optimizer,
                "lr_scheduler": {
                    "scheduler": lr_scheduler,
                    "monitor": lr_scheduler.monitor,
                    "interval": self.config.fit.lr_step_interval,
                },
            }
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": lr_scheduler,
                "interval": self.config.fit.lr_step_interval,
            },
        }
```
