### ISSUE TITLE
TQDM Progress Bar shows negative time and speed after resuming from checkpoint

### ISSUE THREAD

**Issue by ductai199x** [Lightning-AI/lightning#13493] opened 2022-07-01 15:18 UTC
## 🐛 Bug

TQDM Progress Bar shows negative time and speed after resuming from checkpoint

[Screencast from 07-01-2022 10:12:29 PM.webm](https://user-images.githubusercontent.com/29772899/176922594-88ed8008-eeb2-4d35-ab49-f176c03c61b0.webm)

### To Reproduce

Train any model for sometime, then resume. The progress bar will register negative numbers

### Expected behavior

Resuming should NOT cause the progress bar to display negative ETA/speed

### Environment

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.6
* Packages:
        - numpy:             1.23.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.12.0+cu116
        - pytorch-lightning: 1.6.4
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.13
        - version:           #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022

**Comment by awaelchli** [comment] 2022-07-01 23:42
This is a duplicate of #13124. I'm closing this to keep the discussion in #13124. Feel free to subscribe to the issue to get notified about the progress. 

I had already looked into it but couldn't find the reason why the bar shows the incorrect estimates yet.

**Closed by awaelchli** 2022-07-01 23:42 UTC
Labels: needs triage
