### ISSUE TITLE
Torchscript callback deadlock

### ISSUE THREAD

**Issue by pfeatherstone** [Lightning-AI/lightning#17468] opened 2023-04-25 08:57 UTC
### Bug description

I want to create a callback which converts my model to TorchScript and ONNX then saves to file. 
Reading through the docs, the following should work:
```py
class JitCheckpoint(Checkpoint):
    def __init__(self):
        self.lastLoss = 100000

    def on_validation_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule"):
        if trainer.is_global_zero:
            assert "loss/val" in trainer.callback_metrics, "monitor not in callback_metrics"
            assert "acc/val" in trainer.callback_metrics, "monitor not in callback_metrics"
            loss        = trainer.callback_metrics["loss/val"].item()
            acc         = trainer.callback_metrics["acc/val"].item()
            if loss < self.lastLoss:
                print("\nSaving checkpoint last loss {} new loss {}".format(self.lastLoss, loss))
                self.lastLoss = loss
                ckpdir      = trainer.log_dir + "/checkpoints/"
                filePath    = ckpdir + "epoch={}_loss={:.4f}_acc={:.2f}".format(trainer.current_epoch, loss, acc)
                jitPath     = filePath + '.pt'
                onnxPath    = filePath + '.onnx'
                os.makedirs(ckpdir, exist_ok=True)

                input = torch.randn(2, 20*1024, 2)
                pl_module.to_torchscript(file_path=jitPath, method='trace', example_inputs=[input])
                pl_module.to_onnx(file_path=onnxPath, input_sample=input)
        trainer.strategy.barrier()
```
But when I train on multi-GPU i get a deadlock the first time it calls this checkpoint, it hangs for ever spinning both my GPUs at 100% doing nothing. And that's despite calling trainer.strategy.barrier().
Training on 1 GPU or CPU works fine.

### What version are you seeing the problem on?

2.0+

### How to reproduce the bug

```python
Same as above.
```

### Error messages and logs

I get a deadlock.

**Comment by awaelchli** [comment] 2023-04-25 11:11
@pfeatherstone Could you help us verifying this by putting the logic you posted into the this debug script?https://github.com/Lightning-AI/lightning/blob/master/examples/pytorch/bug_report/bug_report_model.py
So that it can be reproduced easily. It would be good to know where it hangs (at `.to_torchscript()`, `.to_onnx()`, somewhere else?).

**Comment by pfeatherstone** [comment] 2023-04-25 12:47
```
import os
import torch
import lightning.pytorch as pl

class RandomDataset(torch.utils.data.Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

class JitCheckpoint(pl.callbacks.Checkpoint):
    def __init__(self):
        self.lastLoss = 100000

    def on_validation_end(self, trainer, pl_module):
        if trainer.is_global_zero:
            print("TorchScript and ONNX checkpoint")
            assert "valid_loss" in trainer.callback_metrics, "monitor not in callback_metrics"
            loss = trainer.callback_metrics["valid_loss"].item()
            if loss < self.lastLoss:
                print("\nSaving checkpoint last loss {} new loss {}".format(self.lastLoss, loss))
                self.lastLoss = loss
                ckpdir      = trainer.log_dir + "/checkpoints/"
                filePath    = ckpdir + "epoch={}_loss={:.4f}".format(trainer.current_epoch, loss)
                jitPath     = filePath + '.pt'
                onnxPath    = filePath + '.onnx'
                os.makedirs(ckpdir, exist_ok=True)

                input = torch.randn(10, 32)
                pl_module.to_torchscript(file_path=jitPath, method='trace', example_inputs=[input])
                pl_module.to_onnx(file_path=onnxPath, input_sample=input)
        trainer.strategy.barrier()

def run():
    train_data  = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data    = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data   = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = pl.Trainer(
        accelerator="gpu",
        devices=2,
        callbacks=[JitCheckpoint()],
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()

```

**Comment by pfeatherstone** [comment] 2023-04-25 12:48
I'm not at work today and my laptop only has 1 GPU so it works. I'll try tomorrow on my desktop which has multiple GPUs. I'm pretty sure this should show the bug.

**Comment by pfeatherstone** [comment] 2023-04-25 12:59
If there was a workaround for the tracing leak, then having it in Lightning would be great.

**Comment by awaelchli** [comment] 2023-04-29 05:10
The program hangs because your code accesses `trainer.log_dir` only on rank 0 (inside the if-statement). `trainer.log_dir` needs to be accessed on all ranks because it has a broadcast operations inside, ensuring that all ranks see the same log_dir in a distributed setting. 

You can fix this issue in your code by moving this line outside of the if statement:

```py
class JitCheckpoint(pl.callbacks.Checkpoint):
    def __init__(self):
        self.lastLoss = 100000

    def on_validation_end(self, trainer, pl_module):
        ckpdir      = trainer.log_dir + "/checkpoints/"
        if trainer.is_global_zero:
            print("TorchScript and ONNX checkpoint")
            assert "valid_loss" in trainer.callback_metrics, "monitor not in callback_metrics"
            loss = trainer.callback_metrics["valid_loss"].item()
            if loss < self.lastLoss:
                print("\nSaving checkpoint last loss {} new loss {}".format(self.lastLoss, loss))
                self.lastLoss = loss
                
                filePath    = ckpdir + "epoch={}_loss={:.4f}".format(trainer.current_epoch, loss)
                jitPath     = filePath + '.pt'
                onnxPath    = filePath + '.onnx'
                os.makedirs(ckpdir, exist_ok=True)

                input = torch.randn(10, 32)
                pl_module.to_torchscript(file_path=jitPath, method='trace', example_inputs=[input])
                pl_module.to_onnx(file_path=onnxPath, input_sample=input)
        trainer.strategy.barrier()

```

**Closed by awaelchli** 2023-04-29 05:10 UTC
Labels: bug

**Comment by pfeatherstone** [comment] 2023-04-29 07:33
Awesome thanks

**Comment by pfeatherstone** [comment] 2023-04-29 07:34
It would be great if ModelCheckpoint had additional options for checkpointing to TorchScript and ONNX

**Comment by pfeatherstone** [comment] 2023-04-29 07:34
This is an easy mistake to make so Lightning providing something out the box would be cool.

**Comment by pfeatherstone** [comment] 2023-06-22 09:30
@awaelchli  How do I move the model to the CPU when running `pl_module.to_torchscript()` and `pl_module.to_onnx()`. The exports complain about not all tensors are on the same device. Thanks
