### ISSUE TITLE
Epochs terminating early incorrectly

### ISSUE THREAD

**Issue by jasonxzhou** [Lightning-AI/lightning#12956] opened 2022-05-02 23:28 UTC
## 🐛 Bug

My understanding is that custom dataloaders are expected to reset themselves and throw `StopIteration` when `__next__` is called and there is nothing more to yield (e.g. at end of an epoch). 
However, starting from `pytorch-lightning == 1.6.0`, Lightning appears to recognize that there are no more batches to yield, and this final `__next__` call at the end of the epoch is no longer made. Subsequently, on the next epoch, when the first such `__next__` call is made, the reset and StopIteration steps are triggered and the epoch ends immediately. 
This results in every other epoch being skipped/terminating early: 
```
Time for epoch 0: 0.14461779594421387
Time for epoch 1: 0.000400543212890625   <- skipped 
Time for epoch 2: 0.11101579666137695
Time for epoch 3: 0.00034236907958984375 <- skipped 
Time for epoch 4: 0.11014986038208008
Time for epoch 5: 0.0003437995910644531  <- skipped 
Time for epoch 6: 0.1101064682006836
Time for epoch 7: 0.00034737586975097656 <- skipped 
Time for epoch 8: 0.1124570369720459
Time for epoch 9: 0.0006518363952636719  <- skipped 
```

### To Reproduce
```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy

from pytorch_lightning import Trainer
from pytorch_lightning.core.lightning import LightningModule

import torch
import os
import time 

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        x = x[0]['random'].float() # unpack random data
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)
    
    def on_train_epoch_start(self):
        self.start_time = time.time()
    
    def on_train_epoch_end(self):
        print(f'Time for epoch {self.current_epoch}: {time.time() - self.start_time}')

    def setup(self, stage=None):
        device_id = self.local_rank
        shard_id = self.global_rank
        num_shards = self.trainer.world_size
        mnist_pipeline = BoringPipeline(batch_size=2, device='gpu', device_id=device_id, shard_id=shard_id, num_shards=num_shards, num_threads=8)
        self.train_loader = DALIGenericIterator(mnist_pipeline, output_map=['random'], size=100, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True)

    def train_dataloader(self):
        return self.train_loader

@pipeline_def
def BoringPipeline(device, shard_id, num_shards):
    return fn.random.coin_flip(shape=32)

def run():
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_val_batches=0,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=10,
        enable_model_summary=False,
    )
    trainer.fit(model)

if __name__ == "__main__":
    run()
```

### Expected behavior
On `pytorch-lightning==1.5.10`, there is no such issue, and we get the following times:
```
Time for epoch 0: 0.12346410751342773
Time for epoch 1: 0.09711241722106934
Time for epoch 2: 0.09668135643005371
Time for epoch 3: 0.09659314155578613
Time for epoch 4: 0.09643316268920898
Time for epoch 5: 0.0983741283416748
Time for epoch 6: 0.09633684158325195
Time for epoch 7: 0.09726572036743164
Time for epoch 8: 0.09633612632751465
Time for epoch 9: 0.10026073455810547
```

### Environment
```
* CUDA:
        - GPU:
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
                - NVIDIA A40
        - available:         True
        - version:           11.5
* Packages:
        - numpy:             1.22.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.11.0+cu115
        - pytorch-lightning: 1.6.2
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #1 SMP Debian 5.15.15-2~bpo11+1 (2022-02-03)
```

### Additional context

cc @justusschock @awaelchli @ninginthecloud @rohitgr7

**Comment by carmocca** [comment] 2022-05-06 16:17
If that's the problem, you can verify it (and work around it) by doing this:

```python
from pytorch_lightning import Trainer
from pytorch_lightning.demos.boring_classes import BoringModel
from pytorch_lightning.loops import FitLoop

model = BoringModel()
trainer = Trainer(max_epochs=10)

class WorkaroundFitLoop(FitLoop):
    @property
    def prefetch_batches(self) -> int:
        return 1

trainer.fit_loop = WorkaroundFitLoop(trainer.fit_loop.min_epochs, trainer.fit_loop.max_epochs)

trainer.fit(model)
```

**Comment by jasonxzhou** [comment] 2022-05-06 18:11
Verified - that is indeed the problem. Overriding `trainer.fit_loop` with `WorkaroundFitLoop` resolves the issue. 

I had worked around the issue by modifying the custom dataloader provided by NVIDIA DALI, since it was not clear to me if this was an intended change in behavior on the PL side.

**Comment by carmocca** [comment] 2022-05-19 18:00
I'm not sure if manually overriding `prefetch_batches` fixes the issue correctly. See this reduced reproduction code:

```python
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy

from pytorch_lightning.utilities.fetching import DataFetcher


@pipeline_def
def BoringPipeline(device, shard_id, num_shards):
    return fn.random.coin_flip(shape=32)


mnist_pipeline = BoringPipeline(batch_size=2, device="gpu", device_id=0, shard_id=0, num_shards=0, num_threads=8)
loader = DALIGenericIterator(
    mnist_pipeline, output_map=["random"], size=6, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True
)

for epoch in range(3):
    for i, _ in enumerate(loader):
        print(epoch, i)

print("-" * 20)

fetcher = DataFetcher(prefetch_batches=0)
fetcher.setup(loader)
for epoch in range(3):
    for i, _ in enumerate(fetcher):
        print(epoch, i)


print("-" * 20)

fetcher = DataFetcher(prefetch_batches=1)
fetcher.setup(loader)
for epoch in range(3):
    for i, _ in enumerate(fetcher):
        print(epoch, i)
```

prints

```bash
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
--------------------
0 0
0 1
0 2
2 0
2 1
2 2
--------------------
1 0
1 1
1 2
2 0
2 1
2 2
```

Batches are missing in both cases.

Since the DALI iterator is sized, when we detect that it is exhausted, we signal to stop fetching by setting `self.done`: https://github.com/PyTorchLightning/pytorch-lightning/blob/eb21135b2aad20aaad45aae44858c090f1e780e5/pytorch_lightning/utilities/fetching.py#L285-L289. This means on the next `__next__` call, we will raise the `StopIteration` ourselves: https://github.com/PyTorchLightning/pytorch-lightning/blob/eb21135b2aad20aaad45aae44858c090f1e780e5/pytorch_lightning/utilities/fetching.py#L275-L277
but the DALI iterator does not know this, and needs this extra `__next__` call to reset its state: https://github.com/NVIDIA/DALI/blob/9d790c7cca5b383c99c79b430117e13f14764d3d/dali/python/nvidia/dali/plugin/base_iterator.py#L250-L251. This is why the first fetch of the next epoch raises the `StopIteration`.

IMO the best solution would be that (1) DALI does the same state reset after returning the last batch by checking the current counter vs total size or/and (2) we manually call a reset method on the DALI iterator when this happens.

I would appreciate input here from a DALI dev: cc @JanuszL as its top contributor

**Comment by JanuszL** [comment] 2022-05-19 18:42
Hi @carmocca,

Thank you for your thorough analysis.
Regarding the options:
-  (1) DALI does the same state reset after returning the last batch by checking the current counter vs total size - I'm thinking about extending auto-reset to have 3 values: `True`, `False`, `Silent`. The silent mode would not rise `StopIteration` and this is probably what we are looking for now. Let me check with the team if this is the way to go.
- (2) we manually call a reset method on the DALI iterator when this happens. - I guess this requires a dedicated code path for DALI (unless the user can provide a custom function for fetching)

**Comment by carmocca** [comment] 2022-05-19 19:34
Thanks for the quick response! I implemented (2) in #13111

**Comment by JanuszL** [comment] 2022-05-19 19:40
> Thanks for the quick response! I implemented (2) in https://github.com/PyTorchLightning/pytorch-lightning/pull/13111

I appreciate the effort, I just don't like the idea of having a dedicated code path just for DALI. I would like DALI to behave like other data sources so it can play nicely in the case where TorchData can.

**Comment by justusschock** [comment] 2022-05-20 11:17
I agree with @JanuszL concerns. Having a dedicated path for any lib, PL does not depend on seems weird to me. 
That would be similar to special-casing logger backends where we decided against doing that in the past.

I think this could be a potential precedence we don't want to set.

@JanuszL Any estimates on how long it might take to implement (1) ?

**Comment by JanuszL** [comment] 2022-05-20 12:25
@justusschock,

> @JanuszL Any estimates on how long it might take to implement (1) ?

The idea should be rather easy to implement by conditionally not rising StopIteration [here](https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/base_iterator.py#L280). Before we move with that change we want to learn more about TorchData and see how well it would be aligned with its behavior. What we don't fully understand (as we are not that much into TorchData) is why DALI needs this special treatment in PL while the Torch loaders work fine.

**Comment by justusschock** [comment] 2022-05-20 13:48
@JanuszL Not sure about `TorchData`, I'd assume it to have the same issues, but for the `torch.utils.Dataloader`, the key is that there is a separate Iterator class [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L393) that will be recreated every time to reset it. Therefore it doesn't matter that the last `next` call is missing since the reset is done on the next `iter` call instead.

**Comment by JanuszL** [comment] 2022-05-20 13:54
@justusschock - thanks for the pointers. We will do our investigation nevertheless, in the meantime, we will sketch the proposed change and see how that works.

**Comment by JanuszL** [comment] 2022-05-20 18:14
https://github.com/NVIDIA/DALI/pull/3923 is an idea of how DALI can deal with the mentioned problem.

**Comment by JanuszL** [comment] 2022-05-24 11:21
> This means that DALI users will always need to set mode="quiet" to use their iterators with PL, correct?

That is one of the ideas, we are still exploring different options.

**Comment by JanuszL** [comment] 2022-05-27 13:18
@carmocca - after some consideration I think we can add `mode="iter"` that would attempt to reset the DALI iterator whenever you call `iter()` on it. It should be more intuitive and aligned with other loaders' behavior.

**Comment by carmocca** [comment] 2022-05-30 16:46
That should work! Please ping me when the fix is released so I can test it out in our codebase.

**Comment by JanuszL** [comment] 2022-06-28 13:11
https://github.com/NVIDIA/DALI/pull/3923 has been merged. It should be available in the next nightly build (tomorrow at earliest) and DALI 1.16.

**Comment by carmocca** [comment] 2022-06-30 20:02
Thanks @JanuszL. I just tried installing nightly (`nvidia-dali-nightly-cuda110==1.16.0.dev20220622`) and running the snippet in https://github.com/Lightning-AI/lightning/issues/12956#issuecomment-1132019916 but the output has not changed. What do users need to set? I didn't find this `mode="iter"` argument you mentioned before.

**Comment by JanuszL** [comment] 2022-06-30 20:12
Hi @carmocca,

It was merged two days ago and you need the nightly build that is no older than 20220628. However, due to other problems the nightly builds have been failing for a couple of days, I hope it will be available soon.
After the internal team discussion we decided that there is no need for an additional iterator mode and just any `iter()` call on the DALI FW iterator should attempt to reset it and warn if it is not possible (DALI pipeline due to its nature rooted deeply in its architecture cannot be reset in the middle of the epoch).

**Comment by JanuszL** [comment] 2022-07-11 08:08
@carmocca,

There should be a fresh nightly build available you can try out. Please check it and let us know if you have any problems.

**Comment by carmocca** [comment] 2022-07-13 14:42
Thank you so much! I manually tried the patch and it seems to be working as expected

**Closed by carmocca** 2022-07-13 14:42 UTC
Labels: bug, data handling

**Comment by 24hours** [comment] 2023-05-16 14:07
This same error occurs when you are using async_dataloader. I am using it because I have observed reduce in latency / iteration.
https://github.com/Lightning-Universe/lightning-bolts/blob/master/pl_bolts/datamodules/async_dataloader.py

I have no clear idea what the fix should be yet.

**Comment by 24hours** [comment] 2023-05-16 16:02
Hi @JanuszL ,

This error is not related to DALI, AsyncDataloader stepped on the same issue. I'm mentioning the issue here in case someone encountered similar issue as it took me 2 days to pin down why my validation step is not running.

**Comment by vturrisi** [comment] 2023-05-29 14:12
Hi @JanuszL. 

Seems like this issue is happening again with Pytorch Lightning>=2.0.0 and Nvidia Dali. I'm not sure the root cause if the same, but I'm seeing the same epoch-skipping behaviour. There's currently this open issue https://github.com/vturrisi/solo-learn/issues/346 and I've also validated it on my end. I can also confirm that this doesn't happen with pytorch-lightning==1.9.0, so it is something that changed in 2.0.

```
nvidia-dali-cuda120==1.26.0
pytorch-lightning>=2.0.0
```

**Comment by JanuszL** [comment] 2023-05-29 16:34
Hi @vturrisi,

I have run this slightly modified sample:
```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator

from pytorch_lightning.loops.fetchers import _PrefetchDataFetcher


@pipeline_def
def BoringPipeline(device, shard_id, num_shards):
    return fn.random.coin_flip(shape=32)


pipeline = BoringPipeline(batch_size=2, device="cpu", device_id=0, shard_id=0, num_shards=0, num_threads=1)

# No fetcher

loader = DALIGenericIterator(pipeline, output_map=["random"], size=6, auto_reset=True)
for epoch in range(3):
    for i, _ in enumerate(loader):
        print(epoch, i)

print("-" * 20)

# Fetcher no prefetch

loader = DALIGenericIterator(pipeline, output_map=["random"], size=6, auto_reset=True)
fetcher = _PrefetchDataFetcher(prefetch_batches=0)
fetcher.setup(loader)
for epoch in range(3):
    for i, _ in enumerate(fetcher):
        print(epoch, i)


print("-" * 20)

# Fetcher with prefetch

loader = DALIGenericIterator(pipeline, output_map=["random"], size=6, auto_reset=True)
fetcher = _PrefetchDataFetcher(prefetch_batches=1)
fetcher.setup(loader)
for epoch in range(3):
    for i, _ in enumerate(fetcher):
        print(epoch, i)
```
And it works just fine. Do you have any similar repro in mind that could reproduce this behavior?

BTW - have you seen the recently introduced [conditional execution](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#conditional-execution) and the [AutoAugument](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/auto_aug/auto_aug.html) capabilities? It is faster and more memory efficient than the previous muxing that you use in your code.

**Comment by vturrisi** [comment] 2023-05-29 18:42
Hey @JanuszL,

Thanks for the example. Is prefetch something like `num_workers` in pytorch?

I'll need to dig a bit deeper because of how everything is structured in solo, so it might be the combination of things that I'm currently using. I see that I'm using `.build()` instead of `.setup()` is there any difference there? I'll try to create a small example to reproduce the error following the design that I have in solo and I'll ping you when I find something.

Yeah, I saw the conditional/AutoAugment update, looks neat. Hopefully, I can implement it soon enough :)

**Comment by vturrisi** [comment] 2023-05-29 20:48
@JanuszL found the issue. The problem happens when using `last_batch_policy=LastBatchPolicy.DROP`. I've attached an example based on https://github.com/NVIDIA/DALI/blob/c19bb9a7ade9cb4ceee36864592d07b8a9527400/docs/examples/frameworks/pytorch/pytorch-various-readers.ipynb

```
import os

import nvidia.dali.fn as fn
import nvidia.dali.types as types
import torch
import torch.nn.functional as F
from nvidia.dali import pipeline_def
from nvidia.dali.plugin.pytorch import DALIClassificationIterator, LastBatchPolicy
from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from torch.optim import Adam

BATCH_SIZE = 64


class LitMNIST(LightningModule):
    def __init__(self):
        super().__init__()

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, 128)
        self.layer_2 = torch.nn.Linear(128, 256)
        self.layer_3 = torch.nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()

        # (b, 1, 28, 28) -> (b, 1*28*28)
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = F.relu(x)
        x = self.layer_2(x)
        x = F.relu(x)
        x = self.layer_3(x)

        x = F.log_softmax(x, dim=1)
        return x

    def training_step(self, batch, batch_idx):
        print(self.current_epoch)
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        return loss

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-3)


# Path to MNIST dataset
data_path = os.path.join(os.environ["DALI_EXTRA_PATH"], "db/MNIST/training/")


@pipeline_def
def GetMnistPipeline(device, shard_id=0, num_shards=1):
    jpegs, labels = fn.readers.caffe2(
        path=data_path, shard_id=shard_id, num_shards=num_shards, random_shuffle=True, name="Reader"
    )
    images = fn.decoders.image(
        jpegs, device="mixed" if device == "gpu" else "cpu", output_type=types.GRAY
    )
    images = fn.crop_mirror_normalize(
        images, dtype=types.FLOAT, std=[0.3081 * 255], mean=[0.1307 * 255], output_layout="CHW"
    )
    if device == "gpu":
        labels = labels.gpu()
    # PyTorch expects labels as INT64
    labels = fn.cast(labels, dtype=types.INT64)
    return images, labels


class DataModule(LightningDataModule):
    def setup(self, stage=None):
        device_id = self.trainer.local_rank
        shard_id = self.trainer.global_rank
        num_shards = self.trainer.world_size
        num_shards = self.trainer.world_size
        mnist_pipeline = GetMnistPipeline(
            batch_size=BATCH_SIZE,
            device="gpu",
            device_id=device_id,
            shard_id=shard_id,
            num_shards=num_shards,
            num_threads=8,
        )

        class LightningWrapper(DALIClassificationIterator):
            def __init__(self, *kargs, **kvargs):
                super().__init__(*kargs, **kvargs)

            def __next__(self):
                out = super().__next__()
                # DDP is used so only one pipeline per process
                # also we need to transform dict returned by DALIClassificationIterator to iterable
                # and squeeze the lables
                out = out[0]
                return [out[k] if k != "label" else torch.squeeze(out[k]) for k in self.output_map]

        self.train_loader = LightningWrapper(
            mnist_pipeline, reader_name="Reader", last_batch_policy=LastBatchPolicy.DROP  # with last_batch_policy=LastBatchPolicy.PARTIAL it works fine
        )

    def train_dataloader(self):
        return self.train_loader


model = LitMNIST()
trainer = Trainer(max_epochs=5, devices=1, accelerator="gpu")
# ddp work only in no-interactive mode, to test it unncoment and run as a script
# trainer = Trainer(devices=8, accelerator="gpu", strategy="ddp", max_epochs=5)
trainer.fit(model, datamodule=DataModule())
```

**Comment by JanuszL** [comment] 2023-05-30 06:49
Let me check it and get back to you soon.

**Comment by JanuszL** [comment] 2023-05-30 11:18
I hope https://github.com/NVIDIA/DALI/pull/4881 should help. Can you applied this changes in your env and make sure that it helps?

**Comment by vturrisi** [comment] 2023-05-30 12:39
Thanks! I'll try to check it soon.

**Comment by vturrisi** [comment] 2023-05-30 20:52
Can confirm the changes fix the issue. Thanks for that!
