### ISSUE TITLE
No `train_dataloader()` method defined.

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14601] opened 2022-09-08 11:39 UTC
### To Reproduce

```py

import os
import torch
import torchvision as tv
import lightning as L
from lightning.app import storage
from lightning_app.runners import MultiProcessRuntime


class LitClassifier(L.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = torch.nn.functional.cross_entropy(self.model(x), y)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)

class DataProcessor(L.LightningWork):
    def __init__(self, working_dir):
        super().__init__()
        self.working_dir = working_dir
        self.train_loader = None

    def run(self):
        train_ds = tv.datasets.CIFAR10(self.working_dir.root_folder, train=True, download=True, transform=tv.transforms.ToTensor())
        train_loader = torch.utils.data.DataLoader(train_ds, batch_size=32)
        self.train_loader = L.app.storage.Payload(train_loader)

class Train(L.LightningWork):
    def __init__(self, working_dir):
        super().__init__()
        self.working_dir = working_dir
        self.best_ckpt_dir = None
        self.has_new_checkpoint = False

    def run(self, train_dataloader):
        classifier = LitClassifier(tv.models.resnet18())
        trainer = L.Trainer(max_epochs=1, default_root_dir=self.working_dir.root_folder)
        trainer.fit(classifier, train_dataloaders=train_dataloader)
        self.best_ckpt_dir = os.listdir(self.working_dir)[-1]
        self.has_new_checkpoint = True

class Deploy(L.LightningWork):
    def __init__(self):
        super().__init__()
        self._model = None

    def run(self, x, best_checkpoint_path):
        if self._model is None:
            self._model = torch.load(best_checkpoint_path)
        preds = self.model(x)
        return preds

class LitTrainDeploy(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.working_dir = storage.Drive('lit://artifacts')
        self.data = DataProcessor(self.working_dir)
        self.train = Train(self.working_dir)
        self.deploy = Deploy()

    def run(self):
        loader = self.data.run()
        self.train.run(loader)
        import pdb; pdb.set_trace()

        if self.train.has_new_checkpoint:
            self.train.has_new_checkpoint = False
            self.deploy.run(torch.rand((10, 10)), self.train.best_ckpt_dir)

if __name__ == '__main__':
    app = L.LightningApp(LitTrainDeploy())
    MultiProcessRuntime(app).dispatch()
```

```
Process Process-3:
Traceback (most recent call last):
  File "/Users/adrian/miniconda3/envs/lightning/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/adrian/miniconda3/envs/lightning/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adrian/repositories/lightning/src/lightning_app/utilities/proxies.py", line 315, in __call__
    raise e
  File "/Users/adrian/repositories/lightning/src/lightning_app/utilities/proxies.py", line 298, in __call__
    self.run_once()
  File "/Users/adrian/repositories/lightning/src/lightning_app/utilities/proxies.py", line 415, in run_once
    self.work.on_exception(e)
  File "/Users/adrian/repositories/lightning/src/lightning_app/core/work.py", line 531, in on_exception
    raise exception
  File "/Users/adrian/repositories/lightning/src/lightning_app/utilities/proxies.py", line 401, in run_once
    ret = work_run(*args, **kwargs)
  File "/Users/adrian/repositories/lightning/examples/repro2.py", line 43, in run
    trainer.fit(classifier, train_dataloaders=train_dataloader)
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 699, in fit
    self._call_and_handle_interrupt(
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 651, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 738, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    verify_loop_configurations(self)
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/configuration_validator.py", line 39, in verify_loop_configurations
    __verify_train_val_loop_configuration(trainer, model)
  File "/Users/adrian/repositories/lightning/src/pytorch_lightning/trainer/configuration_validator.py", line 77, in __verify_train_val_loop_configuration
    raise MisconfigurationException(
lightning_lite.utilities.exceptions.MisconfigurationException: No `train_dataloader()` method defined. Lightning `Trainer` expects as minimum a `training_step()`, `train_dataloader()` and `configure_optimizers()` to be defined.
INFO: Your Lightning App is being stopped. This won't take long.
INFO: Your Lightning App has been stopped successfully!
INFO: Received SIGTERM signal. Gracefully terminating data...
INFO: Received SIGTERM signal. Gracefully terminating train...
Exception ignored in atexit callback: <function end_run at 0x132de4310>
Traceback (most recent call last):
  File "/Users/adrian/miniconda3/envs/lightning/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 336, in end_run
    def end_run(status: str = RunStatus.to_string(RunStatus.FINISHED)) -> None:
  File "/Users/adrian/repositories/lightning/src/lightning_app/utilities/proxies.py", line 467, in _sigterm_signal_handler
    raise LightningSigtermStateException(0)
lightning_app.utilities.exceptions.LightningSigtermStateException: 0

```

### Environment

Latest master for app and pl. 

You can also fill out the list below manually.
-->

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0):
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

### Additional context

[Internal slack conversation.](https://lightning-ai-corp.slack.com/archives/C01HVJ1ADTK/p1662603112257269)

cc @tchaton @rohitgr7

**Comment by awaelchli** [comment] 2022-09-08 11:42
@carmocca What do you think of using a sentinel value instead of None? If then someone passes None by accident, we can catch the error.

**Comment by carmocca** [comment] 2022-09-08 11:51
Duplicate of https://github.com/Lightning-AI/lightning/issues/14602 (already has my thoughts, I agree, but needs to be a warning)

Also, technically not a bugfix but an enhancement

**Closed by carmocca** 2022-09-08 11:51 UTC
Labels: bug, priority: 0
