### ISSUE TITLE
Actor hangs with `ray` using PL v>=1.7

### ISSUE THREAD

**Issue by erezinman** [Lightning-AI/lightning#14292] opened 2022-08-18 15:15 UTC
When invoking a training from within a Ray actor, the training process hangs. The reason for this is that Ray hangs (happens on multiple Ubuntu machines) when forking a process the way you did when calling `device_parser.num_cuda_devices`.  This doesn't happen on v1.6.5.

To sum-up (before delving into the details), the hanging occurs because of the following change between versions:
In v1.6.5 the `gpu` (changed to `cuda` in the newer version) accelerator just calls `torch.cuda.device_count() > 0` directly, while in 1.7.0 and above, this function `torch.cuda.device_count` is called in a forked process  (`utilities/device_parser.py`, line 346, in `num_cuda_devices`): 
```
with multiprocessing.get_context("fork").Pool(1) as pool:
    return pool.apply(torch.cuda.device_count)
```

The way I deduced the problem is by listening to system-signals and printing the traceback when getting `SIGUSR1` within the hanged process. The traceback we obtained was (starting after calling `pl.Trainer(...)`)

```
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
  return fn(self, **kwargs)
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
  self._accelerator_connector = AcceleratorConnector(
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 212, in __init__
  self._set_parallel_devices_and_init_accelerator()
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 525, in _set_parallel_devices_and_init_accelerator
  if not self.accelerator.is_available():
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/accelerators/cuda.py", line 91, in is_available
  return device_parser.num_cuda_devices() > 0
File "<__CONDA__ENV__>/lib/python3.9/site-packages/pytorch_lightning/utilities/device_parser.py", line 346, in num_cuda_devices
  return pool.apply(torch.cuda.device_count)
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/pool.py", line 736, in __exit__
  self.terminate()
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/pool.py", line 654, in terminate
  self._terminate()
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/util.py", line 224, in __call__
  res = self._callback(*self._args, **self._kwargs)
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/pool.py", line 729, in _terminate_pool
  p.join()
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/process.py", line 149, in join
  res = self._popen.wait(timeout)
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/popen_fork.py", line 43, in wait
  return self.poll(os.WNOHANG if timeout == 0.0 else 0)
File "<__CONDA__ENV__>/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
  pid, sts = os.waitpid(self.pid, flag)
```

The hanging is reproduced by forking from within a Ray worker:
```python
import ray
import multiprocessing

@ray.remote
def f():
    with multiprocessing.get_context("fork").Pool(1) as pool:
        return pool.apply(int)

print(ray.get(f.remote()))
```

Thanks!

cc @tchaton @rohitgr7 @justusschock @kaushikb11 @awaelchli @akihironitta

**Comment by awaelchli** [comment] 2022-08-19 09:28
Hi @abustamante-coveo Thanks for also reporting it. I'm going to close your issue as duplicate and paste your comments here as I understand the issue is identical:

From @abustamante-coveo:

> We are currently using ray tune. Ray tune generates trials according to our hyper-parameter grid. In each of of those trials we're training a pytorch model using lightning's Trainer. Starting version 1.7.0, The Trainer fails/gets stuck (we're not sure) and ray tune's trials never finish. Last version of lightning that worked for us is 1.6.5
> If I saw correctly, after 1.6.5 the accelerators.cuda.CUDAAccelerator.is_available method was changed from using torch's device_count to using a new module, device_parser. device_parser.num_cuda_devices() is then used and I have tracked the error to the with block: with multiprocessing.get_context("fork").Pool(1) as pool. That with block either never returns or throws an error (we have a hard time debugging this). It fails in such way that ray tune does not understand it has failed so it stays forever waiting for the trial to begin. This happens in the normal ray tune way of working (a separate process created per trial). If I configure ray tune to run "locally" meaning, all the trials in the same process (not creating a separate process for each trial) then there's no problem. Ray tune's local mode is only meant for debugging and we cannot use it in prod.

**Comment by awaelchli** [comment] 2022-08-19 09:35
We call `torch.cuda.device_count` in this special way

```py
with multiprocessing.get_context("fork").Pool(1) as pool:
    return pool.apply(torch.cuda.device_count)
```

because calling any `torch.cuda` functions creates a CUDA context. We want to avoid this to support forking in PL (#13405). 

However, we also have a check there that, if forking is not supported by the system, we just call the torch.cuda.device_count normally. So it really surprises me that you see these problems. Could you help me understand why it is not possible to fork processes in a ray worker? I guess we just need to find a way to detect that whether it is ok to fork or not.

**Comment by erezinman** [comment] 2022-08-19 14:22
How about using multithreading? Would it change the entire process' context?

**Comment by awaelchli** [comment] 2022-08-19 17:02
It is strange that forking can't work with ray, but there is probably a good reason for it and I'm just not familiar enough with the inner workings there. 

> How about using multithreading? Would it create a Cuda context? @awaelchli

Yes it would, unfortunately (I just tested it). 

Maybe we don't need to fork and can use spawn instead. I have verified that this works well in Jupyter notebooks. I am waiting for the test suite to pass. If you want, you can give this branch a try (or copy the changes manually): #14319 (no guarantees)

**Comment by awaelchli** [comment] 2022-08-19 17:35
Unfortunately I noticed that this solution is also suboptimal. Since spawn takes way longer to create the child process than fork, this method is not going to work for us, and I need to find a different solution. Here are the timing results:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/5495193/185675810-2baf2935-c0db-42b6-9868-75c402e01e72.png">

**Comment by erezinman** [comment] 2022-08-19 17:42
@awaelchli 
I asked for some clarification on their Slack channel, and they referrered me to [this issue](https://github.com/ray-project/ray/issues/27493) 

I think that spawning might not do. I'm not deeply familiar with the inner workings of the different OSs, but there's an issue (whose origin I never got to understand) with pytorch where calling `torch.cuda.is_available` on startup could fix the issue of Cuda not being available later. What I'm saying is that Cuda might not be available in the parent process, but might be available in the spawned child process.

**Comment by awaelchli** [comment] 2022-08-23 12:53
@abustamante-coveo @erezinman I talked with some of the team and we think it is best if we introduce an environment variable "PL_DISABLE_FORK", that, when set to 1 by user or ray, will have PL avoid all forking calls. How does this solution sound?

**Comment by abustamante-coveo** [comment] 2022-08-23 15:52
> @abustamante-coveo @erezinman I talked with some of the team and we think it is best if we introduce an environment variable "PL_DISABLE_FORK", that, when set to 1 by user or ray, will have PL avoid all forking calls. How does this solution sound?

in that case, are we missing on some features that may be added later on? I'm trying to gauge if there would be unintended consequences of having two different ways of executing the same flow

**Comment by awaelchli** [comment] 2022-08-23 16:41
> in that case, are we missing on some features that may be added later on?

No I don't think so. I couldn't see how. Since Ray does not support forking, the feature you are missing out is our `strategy="ddp_fork"` which we introduced with the main motivation to provide better [multi-GPU support in Jupyter notebooks](https://pytorch-lightning.readthedocs.io/en/1.7.0/accelerators/gpu_intermediate.html#distributed-data-parallel-in-notebooks). But I assume one would never use the two together?

> I'm trying to gauge if there would be unintended consequences of having two different ways of executing the same flow

I don't think there could be any influence in this way. Would you mind elaborating what you mean by "two different ways of executing the same flow"?

**Comment by abustamante-coveo** [comment] 2022-08-23 17:25
> > in that case, are we missing on some features that may be added later on?
> 
> No I don't think so. I couldn't see how. Since Ray does not support forking, the feature you are missing out is our `strategy="ddp_fork"` which we introduced with the main motivation to provide better [multi-GPU support in Jupyter notebooks](https://pytorch-lightning.readthedocs.io/en/1.7.0/accelerators/gpu_intermediate.html#distributed-data-parallel-in-notebooks). But I assume one would never use the two together?
> 
> > I'm trying to gauge if there would be unintended consequences of having two different ways of executing the same flow
> 
> I don't think there could be any influence in this way. Would you mind elaborating what you mean by "two different ways of executing the same flow"?

with and without fork. In our case, we would always have to set that environment variable by default. This requires documenting that otherwise, lightning doesn't work for us. I'm questioning about hypothetical future features that may only work when we set up the environment variable or we it's not set up. Is that a risk?

**Comment by awaelchli** [comment] 2022-08-23 20:45
> with and without fork. In our case, we would always have to set that environment variable by default. This requires documenting that otherwise, lightning doesn't work for us.

Yes, that is true :( 
We are hoping that ray-lightning could set this variable for the user.

> I'm questioning about hypothetical future features that may only work when we set up the environment variable or we it's not set up. Is that a risk?

No. This is definitely not our intention. We won't have features hidden behind environment flags except maybe when they are very experimental for some time until becoming stable. This is a special case here in which we can't reliably tell whether Lightning is running with ray and so we can't know that we are not allowed to fork. Hence the variable to explicitly signal that to Lightning. Apologies if it wasn't clear.

**Comment by abustamante-coveo** [comment] 2022-08-24 12:51
> 

if it's set up for us whenever we use ray that would be great. In any case, we will be able to upgrade from 1.6.5 whenever this is merged and live. Thanks!

**Closed** 2022-08-26 15:41 UTC
Labels: bug, priority: 0, 3rd party, strategy: ddp spawn
