### ISSUE TITLE
LR Finder does not support Models that return None in training_step

### ISSUE THREAD

**Issue by NikolasWolke** [Lightning-AI/lightning#17992] opened 2023-07-05 14:53 UTC
### Bug description

Lightning modules may return `None` in the `training_step`, in order to skip the current batch when using automatic optimization. However, the lr finder crashes with a KeyError in that case.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
from typing import Any

import torch
from torch import nn
from torch.nn import functional as F
from torch.optim import AdamW, Optimizer
from torch.optim.lr_scheduler import OneCycleLR
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import Trainer, LightningModule, seed_everything
from pytorch_lightning.tuner import Tuner


class Linear(LightningModule):
    def __init__(self, inputs: int, learning_rate: float):
        super().__init__()
        self.linear = nn.Linear(inputs, 1)
        self.learning_rate = learning_rate

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(x)
    
    def training_step(self, batch: dict[str, torch.Tensor]) -> torch.Tensor | None:
        x = batch["X"]    # shape (batch_size, inputs)
        y = batch["y"]    # shape (batch_size,)
        y_hat = self.forward(x)
        
        loss = F.mse_loss(y, y_hat)
        
        if self.trainer.global_step == 12:    # realistically, this would check for e.g. nans in the loss or in x
            return None
        return loss
    
    def configure_optimizers(self) -> tuple[list[Optimizer], list[dict[str, Any]]]:
        optimizer = AdamW(self.parameters(), lr=self.learning_rate)
        lr_scheduler = OneCycleLR(
            optimizer=optimizer,
            max_lr=self.learning_rate,
            total_steps=self.trainer.estimated_stepping_batches,
        )
        return [optimizer], [{"scheduler": lr_scheduler, "frequency": 1, "interval": "step"}]


class RandomDataset(Dataset):
    def __init__(self, inputs: int, length: int):
        self.len = length
        self.x = torch.randn(length, inputs)
        self.y = 2 * self.x.sum(dim=1) + 3

    def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
        return {"X": self.x[index], "y": torch.zeros(1)}

    def __len__(self) -> int:
        return self.len

if __name__ == "__main__":
    seed_everything()

    dataset = RandomDataset(inputs=10, length=2**12)
    dataloader = DataLoader(dataset, batch_size=256)

    model = Linear(inputs=10, learning_rate=1e-3)

    trainer = Trainer(
        max_epochs=3,
        deterministic=True,
    )
    tuner = Tuner(trainer)
    tuner.lr_find(model, train_dataloaders=dataloader)
```

### Error messages and logs

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[5], line 8
      3 trainer = Trainer(
      4     max_epochs=3,
      5     deterministic=True,
      6 )
      7 tuner = Tuner(trainer)
----> 8 tuner.lr_find(model, train_dataloaders=dataloader)

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/tuner/tuning.py:175, in Tuner.lr_find(self, model, train_dataloaders, val_dataloaders, dataloaders, datamodule, method, min_lr, max_lr, num_training, mode, early_stop_threshold, update_attr, attr_name)
    172 lr_finder_callback._early_exit = True
    173 self._trainer.callbacks = [lr_finder_callback] + self._trainer.callbacks
--> 175 self._trainer.fit(model, train_dataloaders, val_dataloaders, datamodule)
    177 self._trainer.callbacks = [cb for cb in self._trainer.callbacks if cb is not lr_finder_callback]
    179 return lr_finder_callback.optimal_lr

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:520, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    518 model = _maybe_unwrap_optimized(model)
    519 self.strategy._lightning_module = model
--> 520 call._call_and_handle_interrupt(
    521     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    522 )

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:44, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     42         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     43     else:
---> 44         return trainer_fn(*args, **kwargs)
     46 except _TunerExitException:
     47     _call_teardown_hook(trainer)

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:559, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    549 self._data_connector.attach_data(
    550     model, train_dataloaders=train_dataloaders, val_dataloaders=val_dataloaders, datamodule=datamodule
    551 )
    553 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    554     self.state.fn,
    555     ckpt_path,
    556     model_provided=True,
    557     model_connected=self.lightning_module is not None,
    558 )
--> 559 self._run(model, ckpt_path=ckpt_path)
    561 assert self.state.stopped
    562 self.training = False

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:915, in Trainer._run(self, model, ckpt_path)
    913 # hook
    914 if self.state.fn == TrainerFn.FITTING:
--> 915     call._call_callback_hooks(self, "on_fit_start")
    916     call._call_lightning_module_hook(self, "on_fit_start")
    918 _log_hyperparams(self)

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:190, in _call_callback_hooks(trainer, hook_name, monitoring_callbacks, *args, **kwargs)
    188     if callable(fn):
    189         with trainer.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}"):
--> 190             fn(trainer, trainer.lightning_module, *args, **kwargs)
    192 if pl_module:
    193     # restore current_fx when nested context
    194     pl_module._current_fx_name = prev_fx_name

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/callbacks/lr_finder.py:125, in LearningRateFinder.on_fit_start(self, trainer, pl_module)
    124 def on_fit_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
--> 125     self.lr_find(trainer, pl_module)

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/callbacks/lr_finder.py:109, in LearningRateFinder.lr_find(self, trainer, pl_module)
    107 def lr_find(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
    108     with isolate_rng():
--> 109         self.optimal_lr = _lr_find(
    110             trainer,
    111             pl_module,
    112             min_lr=self._min_lr,
    113             max_lr=self._max_lr,
    114             num_training=self._num_training_steps,
    115             mode=self._mode,
    116             early_stop_threshold=self._early_stop_threshold,
    117             update_attr=self._update_attr,
    118             attr_name=self._attr_name,
    119         )
    121     if self._early_exit:
    122         raise _TunerExitException()

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/tuner/lr_finder.py:269, in _lr_find(trainer, model, min_lr, max_lr, num_training, mode, early_stop_threshold, update_attr, attr_name)
    266 lr_finder._exchange_scheduler(trainer)
    268 # Fit, lr & loss logged in callback
--> 269 _try_loop_run(trainer, params)
    271 # Prompt if we stopped early
    272 if trainer.global_step != num_training + start_steps:

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/tuner/lr_finder.py:495, in _try_loop_run(trainer, params)
    493 loop.load_state_dict(deepcopy(params["loop_state_dict"]))
    494 loop.restarting = False
--> 495 loop.run()

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py:201, in _FitLoop.run(self)
    199 try:
    200     self.on_advance_start()
--> 201     self.advance()
    202     self.on_advance_end()
    203     self._restarting = False

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py:354, in _FitLoop.advance(self)
    352 self._data_fetcher.setup(combined_loader)
    353 with self.trainer.profiler.profile("run_training_epoch"):
--> 354     self.epoch_loop.run(self._data_fetcher)

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py:133, in _TrainingEpochLoop.run(self, data_fetcher)
    131 while not self.done:
    132     try:
--> 133         self.advance(data_fetcher)
    134         self.on_advance_end()
    135         self._restarting = False

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py:230, in _TrainingEpochLoop.advance(self, data_fetcher)
    227 if self._num_ready_batches_reached():
    228     self.update_lr_schedulers("epoch", update_plateau_schedulers=False)
--> 230 call._call_callback_hooks(trainer, "on_train_batch_end", batch_output, batch, batch_idx)
    231 call._call_lightning_module_hook(trainer, "on_train_batch_end", batch_output, batch, batch_idx)
    232 trainer._logger_connector.on_batch_end()

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:190, in _call_callback_hooks(trainer, hook_name, monitoring_callbacks, *args, **kwargs)
    188     if callable(fn):
    189         with trainer.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}"):
--> 190             fn(trainer, trainer.lightning_module, *args, **kwargs)
    192 if pl_module:
    193     # restore current_fx when nested context
    194     pl_module._current_fx_name = prev_fx_name

File ~/by/plan-abp-a38/dist/export/python/virtualenvs/dev/3.11.3/lib/python3.11/site-packages/pytorch_lightning/tuner/lr_finder.py:396, in _LRCallback.on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx)
    393 if self.progress_bar:
    394     self.progress_bar.update()
--> 396 loss_tensor = outputs if isinstance(outputs, torch.Tensor) else outputs["loss"]
    397 assert loss_tensor is not None
    398 current_loss = loss_tensor.item()

KeyError: 'loss'
```

So surprisingly, this does not hit the assert in line 397, but fails when unpacking outputs.

### Environment

<details>
  <summary>Current environment</summary>

* Lightning:
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.2
        - torch:             2.0.1
        - torchmetrics:      0.11.4
        - torchvision:       0.15.1a0
* Packages:
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.2
        - torch:             2.0.1
        - torchmetrics:      0.11.4
        - torchvision:       0.15.1a0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         
        - python:            3.11.3
        - release:           6.4.1-arch1-1
        - version:           #1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 16:17:21 +0000

</details>

Also reproduced this on MacOS (also with lightning 2.0.2).

### More info

The API docs of LightningModule state that a training step may return

```
None - Training will skip to the next batch. This is only for automatic optimization.

    This is not supported for multi-GPU, TPU, IPU, or DeepSpeed.
```

So I would expect this to work with the learning rate finder. I would be interested in fixing this bug - probably by simply skipping such batches in the learning rate finder as well.

**Comment by awaelchli** [comment] 2023-07-05 20:25
@NikolasWolke Thanks for finding this. Since you already figured out where the problem is, would you be interested to send a fix for this? That would be awesome!

**Comment by NikolasWolke** [comment] 2023-07-21 11:36
Only found the time to look into a fix today. But will open a PR today.

**Comment by NikolasWolke** [comment] 2023-07-21 12:29
Looks like most of the work was done in https://github.com/Lightning-AI/lightning/pull/17842 already.

However, that introduced a subtle bug since now the list of lrs and losses no longer have the same length and thus the wrong lr will be suggested.

**Closed** 2023-08-03 19:59 UTC
Labels: bug, help wanted, tuner, ver: 2.0.x
