### ISSUE TITLE
Strategy='dp' is not multi-gpu when calling `predict()`

### ISSUE THREAD

**Issue by will-thompson-k** [Lightning-AI/lightning#17318] opened 2023-04-10 09:24 UTC
### Bug description

This seems like a feature, but I would argue it's a bug.

Strategy='dp' allows for multi-gpu training, but when called during inference (i.e. `model.predict()`), it remains single gpu.

This requires one to use strategy='ddp', which is obviously faster for a number of reasons, but if copying the data N times in memory is a constraint, is not ideal.

DP should also be multi-gpu.

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment] 2023-05-01 02:42
The DP strategy gets set up for all trainer stages the same way, unconditionally here:
https://github.com/Lightning-AI/lightning/blob/a020506a81a671e380872aa5e435647b549e14e6/src/pytorch_lightning/strategies/dp.py#L70-L75

And all step methods run through the DP wrapper:
https://github.com/Lightning-AI/lightning/blob/a020506a81a671e380872aa5e435647b549e14e6/src/pytorch_lightning/strategies/dp.py#L131-L149

In order to make use of multi-gpu, you must use `trainer.predict()`, not `model .predict()`. Based on your description, I'm confident that you confused these. This would definitely explain why you saw it only run on a single GPU, and is the expected behavior because the LightningModule itself, when used without the Trainer, will not do any distributed operations by itself. 

I'm closing the issue now for these reasons:
- model.predict() was called instead of trainer.predict(), observations are expected behavior
- We deprecated the DP strategy in 1.9.x and removed it in 2.0.0. The explanation of why can be found in our release notes [here](https://github.com/Lightning-AI/lightning/releases/tag/2.0.0). Hence, we will only fix impactful bugs. Otherwise the use of DP remains discouraged and won't see any further development. 

Let me know if you have any further questions.

**Closed by awaelchli** 2023-05-01 02:42 UTC
Labels: bug, needs triage
