### ISSUE TITLE
torch.enable_grad() not working in predict_step()

### ISSUE THREAD

**Issue by ThyrixYang** [Lightning-AI/lightning#15925] opened 2022-12-06 19:08 UTC
### Bug description

I want to enable gradient in predict_step(), but enable_grad() seems not to be working.

### How to reproduce the bug

```python
import torch
import pytorch_lightning as pl


class Model(pl.LightningModule):
    
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(4, 2)
        
    def predict_step(self, batch, batch_idx):
        with torch.enable_grad():
            x = torch.randn(2, 4, requires_grad=True)
            x.requires_grad = True
            y = self.linear(x)
            loss = y.mean()
            loss.backward()
    
dataset = torch.utils.data.TensorDataset(torch.randn(16, 4))
dataloader = torch.utils.data.DataLoader(dataset, batch_size=2)

trainer = pl.Trainer()
model = Model()

trainer.predict(model, dataloaders=dataloader)
```

### Error messages and logs

```
# Error messages and logs here please
```
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=2)`.
  rank_zero_warn(
Missing logger folder: /home/yangjq/Working/tmp/pytorch/lightning_logs
/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Predicting DataLoader 0:   0%|                                                                                                                                 | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/yangjq/Working/tmp/pytorch/test.py", line 25, in <module>
    trainer.predict(model, dataloaders=dataloader)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 850, in predict
    return call._call_and_handle_interrupt(
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 897, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1139, in _run_stage
    return self._run_predict()
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run_predict
    return self.predict_loop.run()
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 100, in advance
    dl_predictions, dl_batch_indices = self.epoch_loop.run(
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 100, in advance
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 129, in _predict_step
    predictions = self.trainer._call_strategy_hook("predict_step", *step_kwargs.values())
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 408, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/home/yangjq/Working/tmp/pytorch/test.py", line 17, in predict_step
    loss.backward()
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/yangjq/anaconda3/envs/meep2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Predicting DataLoader 0:   0%|          | 0/8 [00:00<?, ?it/s]

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by carmocca** [comment] 2022-12-15 10:19
Duplicate of https://github.com/Lightning-AI/lightning/issues/15765#issuecomment-1323540607. `Trainer(inference_mode=False)` is what you are looking for

**Closed by carmocca** 2022-12-15 10:19 UTC
Labels: needs triage
