### ISSUE TITLE
Adding a Dockerfile to support Lightning on ROCm and AMD GPUs

### ISSUE THREAD

**Issue by sgschwindAMD** [Lightning-AI/lightning#13609] opened 2022-07-11 23:47 UTC
## 🚀 Feature

 The proposed feature would be the addition of a Dockerfile to the directory lightning/dockers that builds Lightning for ROCm.

### Motivation

 The motivation would be ease of use for people wanting to work with Lightning who use ROCm and AMD GPUs.

### Pitch

 The simple addition of a Dockerfile that builds Lightning for ROCm. This Dockerfile would be building upon the latest ROCm Pytorch Dockerfile.

### Alternatives

 None currently

### Additional context

 None currently

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda @justusschock @kaushikb11 @awaelchli @rohitgr7

**Comment by justusschock** [comment] 2022-07-12 09:30
Hi @sgschwindAMD ,

thank you for this issue and your contribution. Personally, I would really like to have this, but I fear that this would look too much like we officially support it. Unfortunately, We cannot do that as of now, since we do need to setup a CI pipeline first so that we can actually verify that PL works well with ROCM (I assume it does, but cannot verify). 

So I would really much like to see this merged, but unfortunately I'd advocate for postponing this.

**Comment by carmocca** [comment] 2022-07-12 10:28
I agree with @justusschock's reasoning. We would like to have some degree of confidence in the integration first.

@sgschwindAMD would you be able to try running the test suite on a machine with AMD GPUs? That would be a good first step to get a feel for what works and what doesn't. This would be similar to how we've added support for the MPS accelerator since there are no CI providers for it currently.

**Comment by akihironitta** [comment] 2022-08-03 23:36
On second thought, we could probably start building the docker image without pushing it to the hub for development. How about merging #13610? @carmocca @justusschock

**Comment by justusschock** [comment] 2022-08-04 07:06
I still wouldn't do so before we tested that PL actually works with ROCm. Even if we just have the file in the repo it would look like being supported

**Comment by carmocca** [comment] 2022-11-02 20:57
Closing as this is a duplicate of #6872 and we don't have access to amd hardware at the moment

**Closed by carmocca** 2022-11-02 20:57 UTC
Labels: ci, accelerator: cuda, pl
