### ISSUE TITLE
self.log issue with torch.compile.

### ISSUE THREAD

**Issue by assassin1991** [Lightning-AI/lightning#18871] opened 2023-10-26 10:55 UTC
### Bug description

Using self.log in a  torch.compile model results in fail. 
Code snippet and error stack pasted below.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
import torch
import os
import warnings
from torch.nn import functional as F  # noqa: N812

from lightning.pytorch import LightningModule
from lightning.pytorch import Trainer, seed_everything
from lightning.pytorch.plugins.precision import MixedPrecisionPlugin
from lightning.pytorch.demos.mnist_datamodule import MNISTDataModule

class LitClassifier(LightningModule):
    """Base model."""

    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_idx):
        x, y = batch
        loss = F.cross_entropy(self(x), y)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        probs = self(x)
        acc = self.accuracy(probs, y)
        self.log("val_acc", acc)

    def test_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        acc = self.accuracy(logits, y)
        self.log("test_acc", acc)

    @staticmethod
    def accuracy(logits, y):
        return torch.sum(torch.eq(torch.argmax(logits, -1), y).to(torch.float32)) / len(y)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)

def run_trainer(model):
    """Run trainer.fit and trainer.test with given parameters."""
    _data_module = MNISTDataModule(batch_size=32)
    trainer = Trainer(
        accelerator="cpu",
        strategy="auto",
        fast_dev_run=3,
    )
    trainer.fit(model, _data_module)
    trainer.test(model, _data_module)

def run_model(compile):
    """Picks appropriate model"""
    _model = LitClassifier()
    if compile is True:
      _model = torch.compile(_model)
    print(f"running model: {_model} with {compile}")
    return run_trainer(_model)

# Run model and print accuracy
seed_everything(42)
run_model(True)
```

### Error messages and logs

```
# Error messages and logs here please
MisconfigurationException                 Traceback (most recent call last)
[<ipython-input-74-18596ff9de40>](https://localhost:8080/#) in <cell line: 3>()
      1 # Run model and print accuracy
      2 seed_everything(42)
----> 3 run_model(True)

35 frames
[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py](https://localhost:8080/#) in <resume in log>(___stack0)
    396         # check the stored metadata and the current one match
    397         elif meta != self[key].meta:
--> 398             raise MisconfigurationException(
    399                 f"You called `self.log({name}, ...)` twice in `{fx}` with different arguments. This is not allowed"
    400             )

MisconfigurationException: You called `self.log(train_loss, ...)` twice in `training_step` with different arguments. This is not allowed
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

pytorch-lightning                2.1.0
torch                            2.1.0+cu118
torchaudio                       2.1.0+cu118
torchdata                        0.7.0
torchmetrics                     1.2.0
torchsummary                     1.5.1
torchtext                        0.16.0
torchvision                      0.16.0+cu118
lightgbm                         4.0.0
lightning                        2.1.0
lightning-utilities              0.9.0
pytorch-lightning                2.1.0

**Comment by jerome-habana** [comment] 2023-10-26 11:02
cc @Borda

**Comment by carmocca** [comment] 2023-10-26 15:06
Duplicate of https://github.com/Lightning-AI/lightning/issues/18835. See the existing comments!

**Closed by carmocca** 2023-10-26 15:06 UTC
Labels: bug, needs triage, ver: 2.1.x
