### ISSUE TITLE
pytorch-lightning 1.7.6 conda package is broken

### ISSUE THREAD

**Issue by deGravity** [Lightning-AI/lightning#14765] opened 2022-09-18 15:10 UTC
### First check

- [X] I'm sure this is a bug.
- [X] I've added a descriptive title to this bug.
- [X] I've provided clear instructions on how to reproduce the bug.
- [X] I've added a code sample.
- [X] I've provided any other important info that is required.

### Bug description

Pytorch lightning cannot be successfully imported after a fresh conda install due to a mismatch between tensorboard and distutils versions. 

I tried going back through versions, and the latest it works on is 1.7.2.

### How to reproduce the bug

```python
Create a new conda environment using the following environment.yml:


name: pltest
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pytorch-lightning=1.7.6
```

Then try to `import pytorch_lightning`

### Error messages and logs

```
>>> import pytorch_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/ben/anaconda3/envs/pltest/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```

### Important info

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): conda distribution
#- PyTorch Lightning Version (e.g., 1.5.0): 1.7.6
#- Lightning App Version (e.g., 0.5.2): N/A
#- PyTorch Version (e.g., 1.10): 1.10.2
#- Python version (e.g., 3.9): 3.10.6
#- OS (e.g., Linux): Linux (under WSL)
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: GTX 1650 Ti Max Q
#- How you installed Lightning(`conda`, `pip`, source): conda 
#- Running environment of LightningApp (e.g. local, cloud): local
```

**Comment by awaelchli** [comment] 2022-09-18 18:15
Hi, which tensorboard version got installed for you?

I can't reproduce the same error, but something is broken. I got (tested py 3.9 and 3.10):


```py

>>> import pytorch_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 148, in <module>
    class DistributedDataParallel(Protocol):
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 156, in DistributedDataParallel
    process_group: Optional[ProcessGroup] = None,
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/typing.py", line 354, in __getitem__
    return self._getitem(self, parameters)
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/typing.py", line 478, in Optional
    arg = _type_check(parameters, f"{self} requires a single type.")
  File "/Users/adrian/miniconda3/envs/conda-pl39/lib/python3.9/typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: typing.Optional requires a single type. Got Ellipsis.
```

**Comment by deGravity** [comment] 2022-09-19 02:47
I get tensorboard 2.10.0 and setuptools 65.3.0 (I think those are the relevant packages in my error)

Here's the full package list from `conda list`

```
# packages in environment at /home/ben/anaconda3/envs/pltest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1           py310h5764c6d_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
blas                      1.0                         mkl  
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.14            ha878542_0    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4          py310h597c629_0    conda-forge
frozenlist                1.3.1           py310h5764c6d_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
future                    0.18.2          py310hff52083_5    conda-forge
google-auth               2.11.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
grpc-cpp                  1.48.1               h05bd8bd_1    conda-forge
grpcio                    1.48.1          py310h5b20944_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310hff52083_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
ld_impl_linux-64          2.38                 h1181459_1  
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libprotobuf               3.21.5               h6239696_3    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310ha2c4b55_0    conda-forge
multidict                 6.0.2           py310h5764c6d_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.23.3          py310h53a5b5f_0    conda-forge
oauthlib                  3.2.1              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
protobuf                  4.21.5          py310hd8f1fbe_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.2              pyhd8ed1ab_0    conda-forge
pyjwt                     2.5.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.10.2          cpu_py310h6894f24_0  
pytorch-lightning         1.7.6              pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_4    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
setuptools                65.3.0          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tensorboard               2.10.0             pyhd8ed1ab_2    conda-forge
tensorboard-data-server   0.6.0           py310h597c629_2    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.8.1           py310h5eee18b_0  
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_3    conda-forge
```

**Comment by deGravity** [comment] 2022-09-19 02:59
I realized that I was using mamba instead of conda to create the environment. When I use conda, the error does not occur. The biggest difference in the packages installed with conda instead of mamba is that pytorch is 1.12.1 instead of 1.10.2:


Package list when installed using conda
```
# packages in environment at /home/ben/anaconda3/envs/pltest2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1           py310h5764c6d_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.14            ha878542_0    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4          py310h597c629_0    conda-forge
frozenlist                1.3.1           py310h5764c6d_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
google-auth               2.11.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
grpc-cpp                  1.48.1               hbad87ad_1    conda-forge
grpcio                    1.48.1          py310h946def9_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310hff52083_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libprotobuf               3.20.1               h6239696_4    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
multidict                 6.0.2           py310h5764c6d_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.23.3          py310h53a5b5f_0    conda-forge
oauthlib                  3.2.1              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
protobuf                  3.20.1          py310hd8f1fbe_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.2              pyhd8ed1ab_0    conda-forge
pyjwt                     2.5.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.12.1          cpu_py310h75c9ab6_0    conda-forge
pytorch-lightning         1.7.6              pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_4    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
tbb                       2021.5.0             h924138e_2    conda-forge
tensorboard               2.10.0             pyhd8ed1ab_2    conda-forge
tensorboard-data-server   0.6.0           py310h597c629_2    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2           py310h5764c6d_2    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_3    conda-forge
```

**Comment by Borda** [comment] 2022-09-19 06:21
Also what python and OS are you using?

**Comment by deGravity** [comment] 2022-09-19 08:16
Ubuntu under WSL2 on Windows. Python 3.10

**Comment by otaj** [comment] 2022-09-20 13:43
I'm closing this issue as it's not really an issue with Lightning.

However, something weird was going on with @awaelchli's installation. If you could please provide me with your `conda list` as well as `conda list -n base` so I could take a look at your issue too, that would be great!

**Closed by otaj** 2022-09-20 13:43 UTC
Labels: bug, priority: 0

**Comment by awaelchli** [comment] 2022-09-20 13:54
@otaj here they are:

<details>
<summary>conda list</summary>
```
# packages in environment at /Users/adrian/miniconda3/envs/conda-pl39:
#
# Name                    Version                   Build  Channel
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h1a28f6b_1
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py39h5161555_1001    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.07.19           hca03da5_0
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.6.15        py39hca03da5_0
cffi                      1.15.1           py39h22df2f2_0
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              35.0.0           py39hfb8cd70_1    conda-forge
frozenlist                1.2.0            py39h1a28f6b_0
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39h2804cbe_3    conda-forge
google-auth               2.11.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.1                      py_1    conda-forge
grpcio                    1.42.0           py39h95c9599_0
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        3.3.0              pyhd8ed1ab_1    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h848a8c0_0
libffi                    3.4.2                hc377ac9_4
libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libprotobuf               3.20.1               hb5ab8b9_4    conda-forge
libzlib                   1.2.12               h03a7124_3    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
markdown                  3.3.4            py39hca03da5_0
multidict                 5.2.0            py39h1a28f6b_3
ncurses                   6.3                  h1a28f6b_3
ninja                     1.11.0               hf86a087_0    conda-forge
numpy                     1.19.5           py39h1f3b974_2    conda-forge
oauthlib                  3.2.1              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h1a28f6b_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.1.2           py39hca03da5_0
protobuf                  3.20.1           py39hc377ac9_0
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.2              pyhd8ed1ab_0    conda-forge
pyjwt                     2.5.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13               hbdb9e5c_1
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.2          cpu_py39h23cb94c_0
pytorch-lightning         1.7.6              pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h5161555_0    conda-forge
readline                  8.1.2                h1a28f6b_1
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
setuptools                63.4.1           py39hca03da5_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.2               h1058600_0
tensorboard               2.10.0             pyhd8ed1ab_2    conda-forge
tensorboard-data-server   0.6.0            py39hfb8cd70_0    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               hb8d0fd4_0
torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h04d1e81_0
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h1a28f6b_1
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.8.1            py39h1a28f6b_0
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h5a0b063_3
```

</details>



<details>
<summary>conda list -n base</summary>

```
# packages in environment at /Users/adrian/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h1a28f6b_1002
ca-certificates           2022.4.26            hca03da5_0
certifi                   2022.5.18.1      py38hca03da5_0
cffi                      1.15.0           py38h22df2f2_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
conda                     4.12.0           py38hca03da5_0
conda-content-trust       0.1.1              pyhd3eb1b0_0
conda-package-handling    1.8.1            py38h1a28f6b_0
cryptography              37.0.1           py38h834c97f_0
idna                      3.3                pyhd3eb1b0_0
libcxx                    12.0.0               hf6beb65_1
libffi                    3.4.2                hc377ac9_2
ncurses                   6.3                  h1a28f6b_2
openssl                   1.1.1o               h1a28f6b_0
pip                       21.2.4           py38hca03da5_0
pycosat                   0.6.3            py38h1a28f6b_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pysocks                   1.7.1            py38hca03da5_0
python                    3.8.13               hbdb9e5c_0
python.app                3                py38h1a28f6b_0
readline                  8.1.2                h1a28f6b_1
requests                  2.27.1             pyhd3eb1b0_0
ruamel_yaml               0.15.100         py38h1a28f6b_0
setuptools                61.2.0           py38hca03da5_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.3               h1058600_0
tk                        8.6.11               hb8d0fd4_1
tqdm                      4.64.0           py38hca03da5_0
urllib3                   1.26.9           py38hca03da5_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h1a28f6b_1
yaml                      0.2.5                h1a28f6b_0
zlib                      1.2.12               h5a0b063_2
```

</details>
