### ISSUE TITLE
Cannot load or use checkpoint with deepspeed stage 2 on 8 GPUs

### ISSUE THREAD

**Issue by jordiclive** [Lightning-AI/lightning#15834] opened 2022-11-26 20:23 UTC
### Bug description

With `strategy= "deepspeed_stage_2"` and training on (8*40Gb A100), `resume_from_checkpoint` fails and also `convert_zero_checkpoint_to_fp32_state_dict` fails. There is no way to use the checkpoint. This checkpoint callback looks like this ```checkpoint_callback = pl.callbacks.ModelCheckpoint(
        dirpath=odir,
        monitor="val_loss_epoch",
        mode="min",
        save_top_k=1,
    )```
The checkpoint file structure looks like this, no other files apart from these:
```
652M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_4_mp_rank_00_optim_states.pt
833M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_5_mp_rank_00_optim_states.pt
699M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_7_mp_rank_00_optim_states.pt
1.2G    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_6_mp_rank_00_optim_states.pt
867M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_3_mp_rank_00_optim_states.pt
5.6G    ./epoch=1-step=20187.ckpt/checkpoint/mp_rank_00_model_states.pt
798M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_2_mp_rank_00_optim_states.pt
930M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt
786M    ./epoch=1-step=20187.ckpt/checkpoint/bf16_zero_pp_rank_1_mp_rank_00_optim_states.pt
```

- When I pass in ```resume_from_checkpoint=epoch=1-step=20187.ckpt```, or ```resume_from_checkpoint=epoch=1-step=20187.ckpt/checkpoint``` I get 
```DeepSpeed was unable to load the checkpoint. Ensure you passed in a DeepSpeed compatible checkpoint or a single checkpoint file with `Trainer(strategy=DeepSpeedStrategy(load_full_weights=True))```

- When I try to convert the checkpoint with 
```
from pytorch_lightning.utilities.deepspeed import convert_zero_checkpoint_to_fp32_state_dict

save_path = "results/20221123_2035/epoch=1-step=20187.ckpt"
output_path = "new_model.pt"
convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
```
I get :
`Unable to find 'latest' file at results/20221123_2035/epoch=1-step=20187.ckpt/latest` . 
Also occurs with `save_path="results/20221123_2035/epoch=1-step=20187.ckpt/checkpoint"`

Manually adding the latest file with checkpoint in it and fp32.py file I get ```[PytorchStreamReader failed reading zip archive: failed finding central directory```

### Environment

```

- PyTorch Lightning Version 1.8.1
- Torch 1.11.0+cu113
- Python version 3.8
- CUDA Version: 11.4
- 8 NVIDIA A100-SXM4-40GBs
```

cc @awaelchli

**Comment by FarzanT** [comment] 2022-12-19 15:02
I wanted to add that even though I've used ZeRO Stage 1 on 4 GPUs, my checkpoint is still sharded into multiple states. Here is the trainer call I used:
```python
    trainer = pl.Trainer(
        default_root_dir=root_dir,
        callbacks=[
            ModelCheckpoint(
                dirpath=root_dir,
                every_n_train_steps=10000//(args.batch_size * args.grad_acc * torch.cuda.device_count()),
                filename=model_name + "_{epoch}_{step}",
                save_last=True)
        ],
        accelerator="gpu",
        accumulate_grad_batches=args.grad_acc,
        strategy=DeepSpeedStrategy(
            stage=1,
            allgather_bucket_size=500000000,
            reduce_bucket_size=500000000,
            pin_memory=True,
            hysteresis=100,
            overlap_comm=True
        ) if args.deepspeed else None,
        devices=-1,
        num_nodes=1,
        precision=16 if args.half_precision else 32,
        max_epochs=args.epoch,
        check_val_every_n_epoch=args.valid_every,
        gradient_clip_val=5,
        plugins=[SLURMEnvironment(requeue_signal=signal.SIGHUP)]
    )

```
When I call `convert_zero_checkpoint_to_fp32_state_dict` on the checkpoint directory, I get the following:
```python
from pytorch_lightning.utilities.deepspeed import convert_zero_checkpoint_to_fp32_state_dict
convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
Processing zero checkpoint '/Users/ftaj/Library/CloudStorage/OneDrive-UniversityofToronto/PycharmProjects/autopath/scTransformers/RegressionTransformer/checkpoints/last.ckpt/checkpoint'
Traceback (most recent call last):
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-1ecd0e27460d>", line 1, in <cell line: 1>
    convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/pytorch_lightning/utilities/deepspeed.py", line 81, in convert_zero_checkpoint_to_fp32_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 406, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 164, in _get_fp32_state_dict_from_zero_checkpoint
    zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 131, in parse_optim_states
    raise ValueError(f"unknown zero stage {zero_stage}")
ValueError: unknown zero stage 1
```

@awaelchli In case you are working on a solution for other stages, please consider ZeRO stage 1 as well.

Thank you,
Farzan

**Comment by majulahsingapuri** [comment] 2023-01-20 08:20
I'm also facing a similar issue. i can convert the model and optimiser states to a single `model.pt` file but i cant load the model with any of the following:

- `MyModel.load_from_checkpoint("...")`
- trainer.test(ckpt_path="...")

while setting the path to the `/epoch-xx.ckpt/`, `/epoch-xx.ckpt/model.pt` or `/epoch-xx.ckpt/checkpoint`.

I have also tried setting 

```python
DeepSpeedStrategy(load_full_weights=True)
```

to no avail. Let me know if i need to furnish more details.

**Comment by MaveriQ** [comment] 2023-05-02 21:20
Here is a bugreport.py to reproduce this problem.

```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    ckpt_callback = ModelCheckpoint(dirpath='.')

    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        strategy='deepspeed',
        accelerator='cuda',
        callbacks=[ckpt_callback],
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)

def resume():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    ckpt_callback = ModelCheckpoint(dirpath='.')

    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=2,
        enable_model_summary=False,
        strategy='deepspeed',
        accelerator='cuda',
        callbacks=[ckpt_callback],
        resume_from_checkpoint='./epoch=0-step=1.ckpt'
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)

if __name__ == "__main__":
    # run()
    resume()
```

For the first time, do only run() and the second time, only resume() and you'll get the error. It would be really nice if there is some update on this issue because it renders lightning useless for large model training that require both deepspeed and resuming from trainin. Thanks!

**Comment by r0mer0m** [comment] 2023-06-26 17:23
Experiencing the same problem. Has this issue been resolved in new versions?

**Comment by awaelchli** [comment] 2023-07-19 09:38
Some improvements for problems mentioned here were addressed:
1. @jordiclive tried to load a file inside the deepspeed checkpoint. We now show a helpful error, giving the user the suggestion to pass in the correct path: #17795
2. @FarzanT's error "unknown stage 1" when running the conversion function was fixed in DeepSpeed: https://github.com/microsoft/DeepSpeed/pull/3936/
3. The repro script posted by @MaveriQ now works (dropping here the updated version for Lightning 2.0), tested with lightning master 2.1.0dev:

	```py
	import os
	
	import torch
	from torch.utils.data import DataLoader, Dataset
	
	from lightning.pytorch import LightningModule, Trainer
	from lightning.pytorch.callbacks import ModelCheckpoint
	
	
	class RandomDataset(Dataset):
	    def __init__(self, size, length):
	        self.len = length
	        self.data = torch.randn(length, size)
	
	    def __getitem__(self, index):
	        return self.data[index]
	
	    def __len__(self):
	        return self.len
	
	
	class BoringModel(LightningModule):
	    def __init__(self):
	        super().__init__()
	        self.layer = torch.nn.Linear(32, 2)
	
	    def forward(self, x):
	        return self.layer(x)
	
	    def training_step(self, batch, batch_idx):
	        loss = self(batch).sum()
	        self.log("train_loss", loss)
	        return {"loss": loss}
	
	    def validation_step(self, batch, batch_idx):
	        loss = self(batch).sum()
	        self.log("valid_loss", loss)
	
	    def test_step(self, batch, batch_idx):
	        loss = self(batch).sum()
	        self.log("test_loss", loss)
	
	    def configure_optimizers(self):
	        return torch.optim.SGD(self.layer.parameters(), lr=0.1)
	
	
	def run():
	    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	
	    model = BoringModel()
	    ckpt_callback = ModelCheckpoint(dirpath='.')
	
	    trainer = Trainer(
	        default_root_dir=os.getcwd(),
	        limit_train_batches=1,
	        limit_val_batches=1,
	        limit_test_batches=1,
	        num_sanity_val_steps=0,
	        max_epochs=1,
	        enable_model_summary=False,
	        strategy='deepspeed',
	        accelerator='cuda',
	        callbacks=[ckpt_callback],
	    )
	    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
	    trainer.test(model, dataloaders=test_data)
	
	def resume():
	    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
	
	    model = BoringModel()
	    ckpt_callback = ModelCheckpoint(dirpath='.')
	
	    trainer = Trainer(
	        default_root_dir=os.getcwd(),
	        limit_train_batches=1,
	        limit_val_batches=1,
	        limit_test_batches=1,
	        num_sanity_val_steps=0,
	        max_epochs=2,
	        enable_model_summary=False,
	        strategy='deepspeed',
	        accelerator='cuda',
	        # devices=2,
	        callbacks=[ckpt_callback],
	    )
	    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data, ckpt_path='./epoch=0-step=1.ckpt')
	    trainer.test(model, dataloaders=test_data)
	
	if __name__ == "__main__":
	    # run()
	    resume()
	
	```

**Closed by awaelchli** 2023-07-19 09:38 UTC
Labels: bug, checkpointing, strategy: deepspeed
