### ISSUE TITLE
Recent legacy checkpoints are not tested in CI

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#12475] opened 2022-03-28 03:07 UTC
## :bug: Bug
Currently, only legacy checkpoints generated with versions from v1.0.0 to v1.4.1 are tested in CI, which are the versions listed in [legacy/back-compatible-versions.txt](https://github.com/PyTorchLightning/pytorch-lightning/blob/2e5728a4841cb1d3b75123ac941cd36f681f9a11/legacy/back-compatible-versions.txt).

For example, see this run on 1.6.0rc1: https://github.com/PyTorchLightning/pytorch-lightning/runs/5695770164?check_suite_focus=true#step:17:584

```
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.0.0] PASSED [ 18%]
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.0.1] PASSED [ 18%]
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.0.2] PASSED [ 18%]
...
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.3.8] PASSED [ 19%]
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.4.0] PASSED [ 19%]
tests/checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[1.4.1] PASSED [ 19%]
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.0.0] PASSED [ 19%]
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.0.1] PASSED [ 19%]
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.0.2] PASSED [ 19%]
...
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.3.8] PASSED [ 20%]
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.4.0] PASSED [ 21%]
tests/checkpointing/test_legacy_checkpoints.py::test_resume_legacy_checkpoints[1.4.1] PASSED [ 21%]
```

The file was introduced in #8535 and it hasn't been updated at all since then.

### Expected behavior
Run tests on legacy checkpoints generated with versions from v1.0.0 to the latest version in CI.

### Environment
n/a

### Additional context
Found this issue while reviewing/documenting our CI/CD.

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda @awaelchli @ananthsub @ninginthecloud

**Comment by carmocca** [comment] 2022-10-13 20:35
Duplicate of https://github.com/Lightning-AI/lightning/issues/11403

**Closed by carmocca** 2022-10-13 20:35 UTC
Labels: bug, priority: 0, ci, tests
