### ISSUE TITLE
Allow `strict=False` in resuming `trainer.fit()` from a checkpoint

### ISSUE THREAD

**Issue by Jose-Bastos** [Lightning-AI/lightning#14879] opened 2022-09-24 09:31 UTC
## 🚀 Feature

Add a `strict=False` option when using `trainer.fit(model,ckpt_path)`

### Motivation

I'm trying to pretrain a model and then load it to a different model (different state_dict and metrics), but when I do `trainer.fit(model.ckpt_path)` I get an error saying the state_dict is different. I know it is different and I want it to be, but I can't pass strict=False as I do with `model.load_from_checkpoint(path,strict=False).`

### Alternatives

Allowing somehting like: `trainer.fit(model,ckpt_path,strict=False)`

If there is already something that does this I couldn't find it.

cc @borda @justusschock @awaelchli @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment] 2022-09-24 12:31
Hey @Jose-Bastos 
Great feature request. This might be a duplicate of #13246 (although I like your title better <3), please have a look there too. There is a proposal there in the comments, feel free to commend there and give your opinion :)

**Comment by Borda** [comment] 2022-11-07 15:54
let's close this one in favor of #13246 and continue the chat there :rabbit:

**Closed by Borda** 2022-11-07 15:54 UTC
Labels: duplicate, feature, won't fix, trainer: fit
