### ISSUE TITLE
Probably broken docker images

### ISSUE THREAD

**Issue by otaj** [Lightning-AI/lightning#15368] opened 2022-10-27 15:11 UTC
### Bug description

We probably have broken CUDA docker images - it seems that our docker images contain PyTorch version compiled with CUDA support, however torchvision without CUDA support. This is happening due to the fact we install them in separate steps and we don't pass PyTorch wheel URL to installation step of `torchvision`.

It is not a high priority since torchvision is not used as often, but it suddenly made `lightning-bolts` testing broken.

### Error messages and logs

```

# Error messages and logs here please

```

cc @carmocca @akihironitta @borda

**Comment by rohitgr7** [comment] 2022-10-27 21:29
failing ci here: https://github.com/Lightning-AI/lightning-bolts/pull/910
is due to this?

**Comment by akihironitta** [comment] 2022-10-28 11:55
For the note, the current failure in https://github.com/Lightning-AI/lightning-bolts/pull/910 shouldn't be caused by this as far as I see the logs and should be fixed by https://github.com/Lightning-AI/lightning-bolts/issues/922 and https://github.com/Lightning-AI/lightning-bolts/pull/912.

**Comment by akihironitta** [comment] 2022-11-07 06:26
I tried to what the issue description states, but I don't even see torchvision installed in the docker image used in Bolts:
https://github.com/Lightning-AI/lightning-bolts/blob/894456fcdcd4c98876864be754e5e4c81c3dd66d/.azure/gpu-tests.yml#L26
```console
$ docker run pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.12-cuda11.6.1 pip list |grep torch
colossalai              0.1.10+torch1.12cu11.3
torch                   1.12.1+cu116
torchmetrics            0.10.0
```

**Comment by akihironitta** [comment] 2022-11-07 06:27
Closing this issue as the Bolts CI now installs the torchvision built with cuda:
```
torchvision             0.13.1+cu116
```
https://dev.azure.com/Lightning-AI/lightning%20Bolts/_build/results?buildId=113243&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=98354d77-e326-51ec-536f-1549451db1fa&l=2129

**Closed by akihironitta** 2022-11-07 06:27 UTC
Labels: ci

**Comment by otaj** [comment] 2022-11-07 10:02
Hi, @akihironitta, I think I agree with you, I think that I maybe grabbed some weird version of the image which installed `examples` (and therefore `torchvision`) I'm perfectly fine with having this closed
