### ISSUE TITLE
KeyError: 'limit_eval_batches'

### ISSUE THREAD

**Issue by muhammadAgfian96** [Lightning-AI/lightning#18114] opened 2023-07-19 04:42 UTC
### Bug description

i tried to use autobatch, sometimes it failed when enter Evaluation loop.
it seems this is typo, it should be `limit_val_batches`? 

https://github.com/Lightning-AI/lightning/blob/dab373de548b352a69c8ea7251937fb4663038dc/src/lightning/pytorch/tuner/batch_size_scaling.py#L154

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
tuner = Tuner(trainer)
    if d_train.tuner.batch_size:
        log.sub_section("BATCH SIZE TUNING (AUTO SEARCH)")
        batch_size_finder = tuner.scale_batch_size(
            model_classifier, 
            datamodule=data_module, 
            mode="binsearch",
            steps_per_trial=6,
            max_trials=4,
            init_val=d_train.batch if d_train.batch <= 32 else 4
        )
```
```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
batch_size_train: 32
batch_size_val: 32
`Trainer.fit` stopped: `max_steps=6` reached.
Batch size 32 succeeded, trying batch size 64
batch_size_train: 64
`Trainer.fit` stopped: `max_steps=6` reached.
Batch size 64 succeeded, trying batch size 128
batch_size_train: 128
`Trainer.fit` stopped: `max_steps=6` reached.
Batch size 128 succeeded, trying batch size 256
batch_size_train: 256
Batch size 256 failed, trying batch size 192
batch_size_train: 192
Batch size 192 failed, trying batch size 160
batch_size_train: 160
Batch size 160 failed, trying batch size 144
batch_size_train: 144
`Trainer.fit` stopped: `max_steps=6` reached.
Batch size 144 succeeded, trying batch size 152
batch_size_train: 152
Batch size 152 failed, trying batch size 148
batch_size_train: 148
Batch size 148 failed, trying batch size 146
batch_size_train: 146
Batch size 146 failed, trying batch size 145
batch_size_train: 145
Batch size 145 failed, trying batch size 144
batch_size_val: 144
Finished batch size finder, will continue with full run using batch size 144
Traceback (most recent call last):
  File "/mnt/ssd_1/clearml-cache/venvs-builds/3.10/task_repository/pytorch-lighting-image-classifier.git/src/train.py", line 111, in <module>
    batch_size_finder = tuner.scale_batch_size(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/tuner/tuning.py", line 93, in scale_batch_size
    self._trainer.fit(model, train_dataloaders, val_dataloaders, datamodule)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 953, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 185, in on_fit_start
    self.scale_batch_size(trainer, pl_module)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 171, in scale_batch_size
    new_size = _scale_batch_size(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/tuner/batch_size_scaling.py", line 89, in _scale_batch_size
    __scale_batch_restore_params(trainer, params)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/tuner/batch_size_scaling.py", line 154, in __scale_batch_restore_params
    setattr(trainer, f"limit_{stage.dataloader_prefix}_batches", params["limit_eval_batches"])
KeyError: 'limit_eval_batches'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.5
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 2.0): 2.0.1
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Ubuntu/Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment] 2023-08-08 13:39
Sure, if the issue is reproducible, that would be great. Thanks!

**Comment by awaelchli** [comment] 2023-09-17 13:29
Looks like with the changes to the bs finder in #16726 this should be fixed 😃

**Closed by awaelchli** 2023-09-17 13:29 UTC
Labels: bug, help wanted, waiting on author, tuner, ver: 2.1.x
