### ISSUE TITLE
CSVLogger doesn't track the step in Fabric unless it is provided manually

### ISSUE THREAD

**Issue by dinhanhx** [Lightning-AI/lightning#17888] opened 2023-06-21 14:05 UTC
### 📚 Documentation

In these following docs
- https://lightning.ai/docs/fabric/stable/api/fabric_methods.html#log-and-log-dict 
- https://lightning.ai/docs/fabric/stable/guide/logging.html

I think there should be some examples about `step` argument. For example, in the following code, to make the csv logger actually prints to disk, you need to specify the `step` argument.

```python
import torch
from lightning.pytorch.demos import WikiText2, Transformer
import lightning as L
from tqdm import tqdm
from lightning.fabric.loggers import CSVLogger

logger = CSVLogger(root_dir=".", flush_logs_every_n_steps=1)
fabric = L.Fabric(accelerator="cuda", devices=1, loggers=logger)
fabric.launch()

dataset = WikiText2()
dataloader = torch.utils.data.DataLoader(dataset, batch_size=64)
model = Transformer(vocab_size=dataset.vocab_size)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

model, optimizer = fabric.setup(model, optimizer)
dataloader = fabric.setup_dataloaders(dataloader)

model.train()
for step, batch in enumerate(tqdm(dataloader)):
    input, target = batch
    optimizer.zero_grad()
    output = model(input, target)
    loss = torch.nn.functional.nll_loss(output, target.view(-1))
    fabric.backward(loss)
    optimizer.step()
    fabric.log("nll_loss", loss.item(), step)
```

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment] 2023-06-28 06:46
@dinhanhx Thanks for the suggestion. 
The step argument is not actually required, but I see what you mean. Thank you for reporting it. I can send a fix for this issue and then the documentation will reflect the intended behavior.

**Closed** 2023-06-28 12:33 UTC
Labels: bug, fabric, logger: csv
