### ISSUE TITLE
Multi node trainer.test(dm) doesn't work with separated file-system

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#8599] opened 2021-07-28 14:09 UTC
### Environment

 - PyTorch Lightning Version (e.g., 1.3.0):
 - PyTorch Version (e.g., 1.8)
 - Python version:
 - OS (e.g., Linux):
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - How you installed PyTorch (`conda`, `pip`, source):
 - If compiling from source, the output of `torch.__config__.show()`:
 - Any other relevant information:

### Additional context

cc @tchaton @rohitgr7

**Comment by awaelchli** [comment] 2021-07-29 12:31
@tchaton is this about loading a checkpoint for trainer.test()? 
Did the user not copy the checkpoint to both nodes?

**Comment by tchaton** [comment] 2021-07-29 18:27
Hey @awaelchli. 

With Grid, the checkpoint is stored only on node 0 and we try to load this from node 1. This fails as it doesn't exists. I think it would be better to load from rank 0 and broadcast to all.

Best,
T.C

**Comment by ananthsub** [comment] 2021-07-29 18:38
@tchaton is there no shared filesystem the checkpoint is written to that's visible across nodes?

for data-parallel use cases, the training type plugin could load on rank 0 only and broadcast. but this does not generalize for options that support larger/sharded models

**Comment by tchaton** [comment] 2021-07-29 19:59
Hey Ananth, you entirely right. The brodcast would not be performed for sharded plugins.

**Comment by carmocca** [comment] 2022-08-22 13:39
I believe this is a duplicate of https://github.com/Lightning-AI/lightning/issues/11136 which has a bit more discussion. Closing in favor of https://github.com/Lightning-AI/lightning/issues/11136

**Closed by carmocca** 2022-08-22 13:39 UTC
Labels: bug, help wanted, priority: 1
