### ISSUE TITLE
Multi-nodes and multi-gpu training never starts

### ISSUE THREAD

**Issue by qingpeijun** [Lightning-AI/lightning#14611] opened 2022-09-08 14:36 UTC
## 🐛 Bug
Multi-nodes and multi-gpu trainning never starts, 2 machines have the same environment and te.py 

### To Reproduce
this is my minimal version: te.py
```
# define any number of nn.Modules (or use your current ones)
encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))
decoder = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), nn.Linear(64, 28 * 28))

# define the LightningModule
class LitAutoEncoder(pl.LightningModule):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = nn.functional.mse_loss(x_hat, x)
        # Logging to TensorBoard by default
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


# init the autoencoder
autoencoder = LitAutoEncoder(encoder, decoder)

# setup data
dataset = MNIST(os.getcwd(), download=True, transform=ToTensor())
train_loader = utils.data.DataLoader(dataset)

# train the model (hint: here are some helpful Trainer arguments for rapid idea iteration)
trainer = pl.Trainer(limit_train_batches=500, accelerator='gpu', devices=2,max_epochs=5,strategy='ddp',num_nodes=2)
trainer.fit(model=autoencoder, train_dataloaders=train_loader)

```
I tried 2 ways on 2 machines 

on 172.18.17.15 , I run with 
```
MASTER_PORT=7445 MASTER_ADDR=172.18.17.15 WORLD_SIZE=4 NODE_RANK=0 PL_TORCH_DISTRIBUTED_BACKEND=nccl python te.py
```
then, on 172.18.17.15, run with
```
MASTER_PORT=7445 MASTER_ADDR=172.18.17.15 WORLD_SIZE=4 NODE_RANK=1 PL_TORCH_DISTRIBUTED_BACKEND=nccl python te.py
```
same for
```
python -m torch.distributed.run --nnodes=2 --master_addr 172.18.17.15 --master_port 7490 --node_rank 0 te.py

python -m torch.distributed.run --nnodes=2 --master_addr 172.18.17.15 --master_port 7490 --node_rank 1 te.py
```
both ways got stuck at the beginning.

### Expected behavior
![IMG_4965](https://user-images.githubusercontent.com/101625489/189144880-73e9cc61-1553-498d-90f3-536ad2727dfd.PNG)
![IMG_4964(20220908-214519)](https://user-images.githubusercontent.com/101625489/189147054-ec59437a-e101-4929-b113-579926a0913d.PNG)

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0):
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

### Additional context

cc @awaelchli @rohitgr7 @akihironitta

**Comment by awaelchli** [comment] 2022-09-09 00:21
@paineQing Code looks good, launch command looks good too! 
A few questions and things to try:

- Can the nodes communicate through nccl? Try setting NCCL_DEBUG=INFO. 
- You could try gloo instead of nccl
- Does single node ddp work? I see in your console that only one local process starts rather than two, what might be the reason for this?

**Comment by awaelchli** [comment] 2022-09-09 00:33
Oh, I think I see what's missing. In your command, `--nproc_per_node 2` is missing, that's why it is creating only one process on each node. Try this:


```
python -m torch.distributed.run --nnodes=2 --nproc_per_node 2 --master_addr 172.18.17.15 --master_port 7490 --node_rank 0 te.py

python -m torch.distributed.run --nnodes=2 --nproc_per_node 2 --master_addr 172.18.17.15 --master_port 7490 --node_rank 1 te.py
```

**Comment by paineQing** [comment] 2022-09-14 07:49
Sorry for not replying in time due to private issue.
First, single node ddp works , and I have set NCCL_DEBUG=INFO, and then run my codes. But I also faced same problems.
![IMG_4990](https://user-images.githubusercontent.com/101625489/190093033-5a435cce-da19-4738-bce4-e64abe8b23d3.PNG)
Second, I tried --nproc_per_node 2. And it also didn't work. The information was listed below. 
![IMG_4989](https://user-images.githubusercontent.com/101625489/190093465-5219d29d-24e4-42e4-a17a-08c158cf9ae3.PNG)
![IMG_4988](https://user-images.githubusercontent.com/101625489/190093513-52d91311-6d07-4716-bbbc-c5332019f49e.PNG)

Thank you for checking them. I will try gloo later, and update my information again. I would like to use nccl not gloo. Could you help me to solve the nccl problem? Thank you very much again.

**Comment by paineQing** [comment] 2022-09-28 13:36
Thanks for replying! seems like the machine can reach the node. 
![321321](https://user-images.githubusercontent.com/101625489/192792161-732ef618-472e-4f1a-8d5c-e87acaa2485e.jpg)

![123123](https://user-images.githubusercontent.com/101625489/192792166-92a5d359-14e8-4703-9e18-79e9a9bd6f7e.jpg)

**Comment by paineQing** [comment] 2022-09-28 13:38
Thanks for replying! seems like the machine can reach the node.
![321321](https://user-images.githubusercontent.com/101625489/192793072-020bb3c8-6512-4989-8d4e-263447fc5ea6.jpg)
![123123](https://user-images.githubusercontent.com/101625489/192793081-cabd9021-6a9e-40ca-8a04-fe09871807e5.jpg)

**Comment by awaelchli** [comment] 2022-09-28 13:58
@paineQing That's good news, one less issue eliminated. In that script, I hardcoded gloo, can you also try with nccl by changing the line to ` torch.distributed.init_process_group("nccl", rank=rank, world_size=world_size)`. 

It is really strange that it does not work with PL, because PL does not do anything fundamentally different than this test script, which is why I'm starting to run out of ideas..

**Comment by paineQing** [comment] 2022-09-28 14:12
> @paineQing That's good news, one less potential issue eliminated. In that script, I hardcoded gloo, can you also try with nccl by changing the line to ` torch.distributed.init_process_group("nccl", rank=rank, world_size=world_size)`.
> 
> It is really strange that it does not work with PL, because PL does not do anything fundamentally different than this test script, which is why I'm starting to run out of ideas..

yeah, it's really strange, sorry that I have just left my lab, I will try it and update ASAP! Thank you!

**Comment by paineQing** [comment] 2022-09-29 02:05
I've changed the line to "nccl", and it got stuck on the node 1.
![IMG_5340](https://user-images.githubusercontent.com/101625489/192921674-05e1d277-16b5-4280-9794-ad522f074d7c.PNG)
![IMG_5341](https://user-images.githubusercontent.com/101625489/192921714-bacb44a9-3531-4822-a48e-d337265e2a99.PNG)

**Comment by paineQing** [comment] 2022-09-29 02:06
> @paineQing That's good news, one less potential issue eliminated. In that script, I hardcoded gloo, can you also try with nccl by changing the line to ` torch.distributed.init_process_group("nccl", rank=rank, world_size=world_size)`.
> 
> It is really strange that it does not work with PL, because PL does not do anything fundamentally different than this test script, which is why I'm starting to run out of ideas..

I've changed the line to "nccl", and it got stuck on the node 1.
![IMG_5340](https://user-images.githubusercontent.com/101625489/192922176-42f4103c-d922-4d96-b5d3-32d01695a63c.PNG)
![IMG_5341](https://user-images.githubusercontent.com/101625489/192922186-5d13b3cd-aa86-4e51-9377-aaaa3595900e.PNG)

**Comment by awaelchli** [comment] 2022-09-29 20:51
@paineQing So I think that explains why Lightning was also stuck. NCCL seems to have a problem on your machine(s). I never had this problem but you could try running with `NCCL_DEBUG=WARN`, then it might show more information. Plus, you could try `NCCL_IB_DISABLE=1`

**Comment by paineQing** [comment] 2022-10-01 14:00
Okay, thanks for your patience! I will work on the NCCL problem and update later.

**Comment by awaelchli** [comment] 2022-10-25 02:00
@paineQing Have you made progress on this? I have one more idea what could be wrong. 

NCCL requires some extra ports to be open in the firewall. It is explained [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#ip-ports).

On both of your nodes, run this:

```
vim /etc/sysctl.conf
```
Add the line `net.ipv4.ip_local_port_range = 50000 51000` if it's not there yet.

```
sysctl --system
ufw allow 50000:51000/tcp
```
You may need to run the above with root (sudo).

This opens the port range for NCCL to use for communication. Now, rerun your script. And also set `NCCL_SOCKET_IFNAME` to the name of the network interface.

**Comment by paineQing** [comment] 2022-10-25 02:27
Thanks for your idea! I will try it and update, but seems like the problem is not on NCCL, cause I rewrote my code and used DeepSpeed for multi-nodes , it communicates through NCCL and it works well on my machines.

**Comment by awaelchli** [comment] 2023-07-23 01:31
Closing this now, since we have established here that the basic pytorch-only script with NCCL posted above hanged too. Therefore I conclude issues must be outside of PyTorch/PL.

**Closed by awaelchli** 2023-07-23 01:31 UTC
Labels: bug, distributed
