### ISSUE TITLE
Better LightningCLI error message when subcommand not given

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18446] opened 2023-08-31 11:12 UTC
### Description & Motivation

The user gets this message if they forget to pass the subcommand:

```
python examples/pytorch/bug_report/bug_report_model.py
```
```
usage: bug_report_model.py [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict} ...
bug_report_model.py: error: '"subcommand" is required but not given or its value is None.'
```

For a beginner, even if they follow the tutorial it is maybe not obvious what a subcommand is.

### Pitch

Adjust the error message to mention an action the user can take. For example, we could list the possible choices. 

### Additional context

Came up internally in Slack. The user mistakenly concluded that they had to set `run=False` as a workaround but that shouldn't be the default experience.

cc @borda @carmocca @mauvilsa

**Comment by 0x404** [comment] 2023-09-04 10:23
hi, @awaelchli 
Can I working on this? But I can't reproduce this using `examples/pytorch/bug_report/bug_report_model.py`. It seems like a problem related to cli launch, but this file explicitly use `trainer.fit` and `trainer.test`.

**Comment by awaelchli** [comment] 2023-09-04 10:29
@0x404 Yes, this only applies to scripts that have a CLI. Something as simple as this already reproduces it:

```py
from lightning.pytorch import LightningModule
from lightning.pytorch.cli import LightningCLI

class BoringModel(LightningModule):
    pass

LightningCLI(BoringModel)
```

Thanks for your interest in working on this!

**Comment by carmocca** [comment] 2023-09-04 12:46
@mauvilsa How would you recommend that this is done? Asking because this error is raised inside jsonargparse, so maybe there's a better way than catching it and reraising with a different wording

**Comment by mauvilsa** [comment] 2023-09-05 05:08
This should be fixed in jsonargparse. Fixing it here would just break if there is a change in jsonargparse. Anyway, improving the message would be beneficial for any CLI implemented with jsonargparse that has subcommands.

**Comment by mauvilsa** [comment] 2023-09-05 10:28
@0x404 if you want to work on this in the jsonargparse repo, some pointers. The relevant code is here [/jsonargparse/_core.py#L1035-L1037](https://github.com/omni-us/jsonargparse/blob/6ed515b78d281e10b0cdc4fa3e8ae006fa29ed66/jsonargparse/_core.py#L1035-L1037). What could be done is: inside the `except` first get the action corresponding to `reqkey` like `action = _find_action(self, reqkey)`. Then if the action has choices, for the exception use a more specific message. For example for the case of `LightningCLI` could be something like `error: expected 'subcommand' to be one of {fit,validate,test,predict}`.

**Comment by 0x404** [comment] 2023-09-05 11:27
Thanks @mauvilsa , I would like to give it a try!

**Comment by 0x404** [comment] 2023-09-05 11:58
It might require a few days because I need to familiarize myself with jsonargparse. I hope this won't cause any delays.

**Comment by mauvilsa** [comment] 2023-09-05 13:11
No worries, there is no hurry. Feel free to ask if you need help.

**Comment by 0x404** [comment] 2023-09-05 14:01
Hi, @awaelchli. After quickly reading the code, I made an attempt to fix this: https://github.com/omni-us/jsonargparse/pull/371. Is this okay?

**Comment by 0x404** [comment] 2023-09-11 05:53
This issue was resolved in https://github.com/omni-us/jsonargparse/pull/371. When using `jsonargparse >= 4.25.0`, the error message for the `lightning CLI` has been updated from `'error: '"subcommand" is required but not given or its value is None.'` to `'error: 'expected "subcommand" to be one of {fit,validate,test,predict}, but it was not provided.''`

**Closed** 2023-09-11 06:32 UTC
Labels: feature, lightningcli

**Comment by awaelchli** [comment] 2023-09-11 10:24
Thanks a lot @0x404, great contribution!
