### ISSUE TITLE
Schedulers don't work

### ISSUE THREAD

**Issue by ririya** [Lightning-AI/lightning#18570] opened 2023-09-15 22:03 UTC
### Bug description

I'm on pytorch_lightning 2.09.

I've configured my optimizer with the below code on my plmodule. The learning rate is never updated... 

```
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=10,
            num_training_steps=self.trainer.max_epochs
        )    
        return dict(optimizer=optimizer, lr_scheduler=dict(scheduler=scheduler, interval="step", frequency=1))
```

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by awaelchli** [comment] 2023-09-17 22:48
@ririya Can you provide a code that reproduces this problem? Most importantly, please thare the code including `get_linear_schedule_with_warmup`. Right now there is not much we can work with to help you here.

**Comment by ririya** [comment] 2023-09-18 11:22
I made some changes and it started working, maybe some imports or their order are affecting it? I can't afford to deep much deeper into it, but here are the non working and working codes:

NOT WORKING:
```
import os
import logging
import json
import torch
import torch.nn as nn
import numpy as np
from typing import List, Tuple
from functools import reduce
import pytorch_lightning as pl
from nltk import edit_distance
from collections import Counter, defaultdict
from torch.optim.lr_scheduler import StepLR, CosineAnnealingLR
from transformers.optimization import get_linear_schedule_with_warmup
from traineval.training.distributed import get_global_rank



class EntityResolutionNet(pl.LightningModule):
    def __init__(self, model, **kwargs):
        super().__init__()
        self.model = model
        self.save_hyperparameters(kwargs)
        self.lr = self.hparams.get("lr", 1e-4)
        self.lr_scheduler_step = self.hparams.get("lr_scheduler_step")
        self.lr_scheduler_gamma = self.hparams.get("lr_scheduler_gamma")
        # self.validation_step_outputs = {"val_loss": [], "total_val_correct": [], "total_correct_words": [], "total_val_samples": [], "total_samples_words":[]}
        self.validation_step_outputs = defaultdict(list)
        self.val_corr_per_class = {}
        self.dev = next(model.parameters()).device

        self.steps = 0
        self.log_every = 10
        self.total_loss = 0
        self.total_correct = 0
        self.total_samples = 0
        self.total_correct_words=0
        self.total_samples_words=0        
       
        self.result = []

    def training_step(self, batch, batch_idx):
         

        input_ids = batch['anchor_ids']
        attention_mask = batch['anchor_mask']
        labels = batch['positive_ids']

        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        self.total_loss += loss.item()      
        
        # Calculate accuracy
        predicted_ids = torch.argmax(logits, dim=-1)
        #check if all elements in second dimension are equal

        correct = torch.sum(predicted_ids == labels)
        self.total_correct += correct.item()
        self.total_samples += labels.numel()
        correct = torch.sum(torch.all(predicted_ids == labels, dim=1))  
        self.total_correct_words += correct.item()
        self.total_samples_words += predicted_ids.size(0)

        self.steps += 1

        if self.steps % self.log_every == 0:
        # if True:
            #      
            print("Train Loss", self.total_loss / self.total_samples)   
            print("Accuracy/train", self.total_correct / self.total_samples)     
            print('Word Accuracy/train', self.total_correct_words / self.total_samples_words)
        
            self.log("Train_Loss", self.total_loss / self.total_samples, prog_bar=True, logger=True, sync_dist=True)
            self.log("Train_Accuracy", self.total_correct / self.total_samples, prog_bar=True, logger=True, sync_dist=True)
            self.log('Train_Word_Accuracy', self.total_correct_words / self.total_samples_words, prog_bar=True, logger=True, sync_dist=True)

            self.total_loss = 0
            self.total_correct = 0
            self.total_samples = 0
            self.total_correct_words=0
            self.total_samples_words=0


        return loss

    def validation_step(self, batch, batch_idx, dataset_idx=0):
        input_ids = batch['anchor_ids']
        attention_mask = batch['anchor_mask']
        labels = batch['positive_ids']
        gt_in_train_batch = batch['gt_in_train']
        ocr_errors = batch['ocr_errors'] if 'ocr_errors' in batch else None
        missing_mappings = batch['missing_mappings'] if 'missing_mappings' in batch else None

        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)

        loss = outputs.loss
        logits = outputs.logits

        total_val_loss = loss.item()

        # Calculate accuracy
        predicted_ids = torch.argmax(logits, dim=-1)
        correct = torch.sum(predicted_ids == labels)
        total_val_correct = correct.item()
        total_val_samples = labels.numel()
        # word accuracy
        correct_words = torch.all(predicted_ids == labels, dim=1)
        total_correct_words = torch.sum(correct_words).item()
        total_samples_words = predicted_ids.size(0)

        #word accuracy in train
        #get sum of all predicted_ids == labels & the respective total_words_in_train==True
        correct_words_in_train = torch.sum(torch.all(predicted_ids == labels, dim=1) & gt_in_train_batch)
        total_correct_words_in_train = correct_words_in_train.item()
        total_words_in_train = torch.sum(gt_in_train_batch).item()

        self.validation_step_outputs["val_loss"].append(total_val_loss)
        self.validation_step_outputs["total_val_correct"].append(total_val_correct)
        self.validation_step_outputs["total_correct_words"].append(total_correct_words)
        self.validation_step_outputs["total_val_samples"].append(total_val_samples)
        self.validation_step_outputs["total_samples_words"].append(total_samples_words)
        self.validation_step_outputs["total_correct_words_in_train"].append(total_correct_words_in_train)
        self.validation_step_outputs["total_words_in_train"].append(total_words_in_train)

        correct_words = correct_words.cpu().numpy()
        if ocr_errors is not None:
            corrected_ocr = correct_words & ocr_errors.cpu().numpy() 
            total_corrected_ocr = np.sum(corrected_ocr)
            self.validation_step_outputs["total_corrected_ocr"].append(total_corrected_ocr)
            total_ocr_errors = ocr_errors.sum().item()
            self.validation_step_outputs["total_ocr_errors"].append(total_ocr_errors)
        if missing_mappings is not None:
            corrected_missing_mappings = correct_words & missing_mappings.cpu().numpy() 
            total_corrected_missing_mappings = np.sum(corrected_missing_mappings)
            self.validation_step_outputs["total_corrected_missing_mappings"].append(total_corrected_missing_mappings) 
            total_missing_mappings = missing_mappings.sum().item()         
            self.validation_step_outputs["total_missing_mappings"].append(total_missing_mappings)      



    def on_validation_epoch_end(self):
        results = {
            "val_loss": sum(self.validation_step_outputs["val_loss"])*1.0 / sum(self.validation_step_outputs["total_val_samples"]),
            "val_accuracy": sum(self.validation_step_outputs["total_val_correct"])*1.0 / sum(self.validation_step_outputs["total_val_samples"]),
            "val_word_accuracy": sum(self.validation_step_outputs["total_correct_words"])*1.0 / sum(self.validation_step_outputs["total_samples_words"]),
            "val_words_in_train_acc": sum(self.validation_step_outputs["total_correct_words_in_train"])*1.0 / sum(self.validation_step_outputs["total_words_in_train"]),
        }
        if 'total_corrected_ocr' in self.validation_step_outputs:
            results["ocr_acc"] = sum(self.validation_step_outputs["total_corrected_ocr"])*1.0 / sum(self.validation_step_outputs["total_ocr_errors"])
        if 'total_corrected_missing_mappings' in self.validation_step_outputs:
            results["missing_mapping_acc"] = sum(self.validation_step_outputs["total_corrected_missing_mappings"])*1.0 / sum(self.validation_step_outputs["total_missing_mappings"])

        self.log('current_epoch', self.current_epoch, on_step=False, on_epoch=True, logger=True, prog_bar=True)
        # # Log final validation metrics
        # if get_global_rank() == 0:            
        self.log_dict(
        results,
        prog_bar=True,
        logger=True,
        sync_dist=False,
        on_step=False, 
        on_epoch=True,
        )

        logging.info(f"Eval Metrics: {json.dumps(results, indent=2)}")



    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        # scheduler = StepLR(optimizer, step_size=self.lr_scheduler_step, gamma=0.5)
        # scheduler = CosineAnnealingLR(optimizer, T_max=self.trainer.max_epochs)
        # lr_scheduler = {'scheduler': scheduler, 'interval': 'epoch', 'monitor': 'val_loss'}
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=self.n_warmup_steps,
            num_training_steps=self.trainer.max_epochs
        )

        return dict(optimizer=optimizer, lr_scheduler=dict(scheduler=scheduler, interval="step"))
        # return [optimizer], [scheduler]
```


WORKING:

```
import faiss
from collections import defaultdict
import logging
import json
from tqdm import tqdm, trange
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl
# import lightning.pytorch as pl
from transformers import AutoTokenizer, AutoModel
from transformers.optimization import get_linear_schedule_with_warmup
import numpy as np
import time


class EntityResolutionNet(pl.LightningModule):

    def __init__(self, model, **kwargs):
        super().__init__()
        self.model = model
        self.similarity_fct = torch.nn.CosineSimilarity()
        self.loss_fn = torch.nn.CrossEntropyLoss()
        self.similarity_scale: float = 20.0
        self.lr: float = kwargs['lr']
        self.scheduler_type = kwargs['scheduler_type']        
        # self.lr = 0.001
        self.n_warmup_steps: int = 10
        self.validation_step_outputs = defaultdict(list)
        self.index_cos = None        
        self.all_sentences = []
        self.all_embeddings = []
        self.steps = 0
        self.log_every = 10
        self.total_loss = 0
        self.total_correct = 0
        self.total_samples = 0
        self.total_correct_words=0
        self.total_samples_words=0        
        self.scheduler = None
        self.save_hyperparameters(kwargs)

    def training_step(self, batch, batch_idx):
         
        input_ids = batch['anchor_ids']
        attention_mask = batch['anchor_mask']
        labels = batch['positive_ids']

        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        self.total_loss += loss.item()      
        
        # Calculate accuracy
        predicted_ids = torch.argmax(logits, dim=-1)
        #check if all elements in second dimension are equal

        correct = torch.sum(predicted_ids == labels)
        self.total_correct += correct.item()
        self.total_samples += labels.numel()
        correct = torch.sum(torch.all(predicted_ids == labels, dim=1))  
        self.total_correct_words += correct.item()
        self.total_samples_words += predicted_ids.size(0)

        self.steps += 1

        if self.steps % self.log_every == 0:
   
            print("Train Loss", self.total_loss / self.total_samples)   
            print("Accuracy/train", self.total_correct / self.total_samples)     
            print('Word Accuracy/train', self.total_correct_words / self.total_samples_words)
        
            self.log("Train_Loss", self.total_loss / self.total_samples, prog_bar=True, logger=True, sync_dist=True)
            self.log("Train_Accuracy", self.total_correct / self.total_samples, prog_bar=True, logger=True, sync_dist=True)
            self.log('Train_Word_Accuracy', self.total_correct_words / self.total_samples_words, prog_bar=True, logger=True, sync_dist=True)

            self.total_loss = 0
            self.total_correct = 0
            self.total_samples = 0
            self.total_correct_words=0
            self.total_samples_words=0


        return loss

    def validation_step(self, batch, batch_idx, dataset_idx=0):
        pass
        input_ids = batch['anchor_ids']
        attention_mask = batch['anchor_mask']
        labels = batch['positive_ids']
        gt_in_train_batch = batch['gt_in_train']
        ocr_errors = batch['ocr_errors'] if 'ocr_errors' in batch else None
        missing_mappings = batch['missing_mappings'] if 'missing_mappings' in batch else None

        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)

        loss = outputs.loss
        logits = outputs.logits

        total_val_loss = loss.item()

        # Calculate accuracy
        predicted_ids = torch.argmax(logits, dim=-1)
        correct = torch.sum(predicted_ids == labels)
        total_val_correct = correct.item()
        total_val_samples = labels.numel()
        # word accuracy
        correct_words = torch.all(predicted_ids == labels, dim=1)
        total_correct_words = torch.sum(correct_words).item()
        total_samples_words = predicted_ids.size(0)

        #word accuracy in train
        #get sum of all predicted_ids == labels & the respective total_words_in_train==True
        correct_words_in_train = torch.sum(torch.all(predicted_ids == labels, dim=1) & gt_in_train_batch)
        total_correct_words_in_train = correct_words_in_train.item()
        total_words_in_train = torch.sum(gt_in_train_batch).item()

        self.validation_step_outputs["val_loss"].append(total_val_loss)
        self.validation_step_outputs["total_val_correct"].append(total_val_correct)
        self.validation_step_outputs["total_correct_words"].append(total_correct_words)
        self.validation_step_outputs["total_val_samples"].append(total_val_samples)
        self.validation_step_outputs["total_samples_words"].append(total_samples_words)
        self.validation_step_outputs["total_correct_words_in_train"].append(total_correct_words_in_train)
        self.validation_step_outputs["total_words_in_train"].append(total_words_in_train)

        correct_words = correct_words.cpu().numpy()
        if ocr_errors is not None:
            corrected_ocr = correct_words & ocr_errors.cpu().numpy() 
            total_corrected_ocr = np.sum(corrected_ocr)
            self.validation_step_outputs["total_corrected_ocr"].append(total_corrected_ocr)
            total_ocr_errors = ocr_errors.sum().item()
            self.validation_step_outputs["total_ocr_errors"].append(total_ocr_errors)
        if missing_mappings is not None:
            corrected_missing_mappings = correct_words & missing_mappings.cpu().numpy() 
            total_corrected_missing_mappings = np.sum(corrected_missing_mappings)
            self.validation_step_outputs["total_corrected_missing_mappings"].append(total_corrected_missing_mappings) 
            total_missing_mappings = missing_mappings.sum().item()         
            self.validation_step_outputs["total_missing_mappings"].append(total_missing_mappings)      



    def on_validation_epoch_end(self):
        results = {
            "val_loss": sum(self.validation_step_outputs["val_loss"])*1.0 / sum(self.validation_step_outputs["total_val_samples"]),
            "val_accuracy": sum(self.validation_step_outputs["total_val_correct"])*1.0 / sum(self.validation_step_outputs["total_val_samples"]),
            "val_word_accuracy": sum(self.validation_step_outputs["total_correct_words"])*1.0 / sum(self.validation_step_outputs["total_samples_words"]),
            "val_words_in_train_acc": sum(self.validation_step_outputs["total_correct_words_in_train"])*1.0 / sum(self.validation_step_outputs["total_words_in_train"]),
        }
        if 'total_corrected_ocr' in self.validation_step_outputs:
            results["ocr_acc"] = sum(self.validation_step_outputs["total_corrected_ocr"])*1.0 / sum(self.validation_step_outputs["total_ocr_errors"])
        if 'total_corrected_missing_mappings' in self.validation_step_outputs:
            results["missing_mapping_acc"] = sum(self.validation_step_outputs["total_corrected_missing_mappings"])*1.0 / sum(self.validation_step_outputs["total_missing_mappings"])

        self.log('current_epoch', self.current_epoch, on_step=False, on_epoch=True, logger=True, prog_bar=True)
       
        self.log_dict(
        results,
        prog_bar=True,
        logger=True,
        sync_dist=False,
        on_step=False, 
        on_epoch=True,
        )

        if self.scheduler:

            lr = self.lr_schedulers().get_last_lr()[0]

            self.log('learning_rate', lr, on_step=False, on_epoch=True, logger=True, prog_bar=True)  # Logging the learning rate


        # logging.info(f"Eval Metrics: {json.dumps(results, indent=2)}")

    
    def configure_optimizers(self):
        """

        :return:
        """
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        if self.scheduler_type == 'cosine':
            from torch.optim.lr_scheduler import StepLR, CosineAnnealingLR, LinearLR
            self.scheduler = CosineAnnealingLR(optimizer, T_max=self.trainer.max_epochs)
            return dict(optimizer=optimizer, lr_scheduler=dict(scheduler=self.scheduler, interval="epoch"))
        else:
            return optimizer


    # def configure_optimizers(self):
    #     optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
    #     # scheduler = StepLR(optimizer, step_size=self.lr_scheduler_step, gamma=0.5)
    #     # scheduler = LinearLR(optimizer, 0.1, 0.9, total_iters=4)
    #     # scheduler = CosineAnnealingLR(optimizer, T_max=self.trainer.max_epochs)

    #     scheduler = get_linear_schedule_with_warmup(
    #         optimizer,
    #         # num_warmup_steps=self.n_warmup_steps,
    #         num_warmup_steps=10,
    #         num_training_steps=self.trainer.max_epochs
    #     )

    #     lr_scheduler = {'scheduler': scheduler, 'interval': 'step'}
    #     # return {'optimizer': optimizer, 'lr_scheduler': scheduler}

    #     return dict(optimizer=optimizer, lr_scheduler=dict(scheduler=scheduler, interval="step", frequency=1))
    #     # return [optimizer], [scheduler]


```

**Comment by awaelchli** [comment] 2023-09-18 12:00
You set the num training steps to max_epochs but the interval for scheduling to "step". Is this intentional? This seems very odd. Can you check please?

**Comment by ririya** [comment] 2023-09-18 12:04
@awaelchli Yes the interval is wrong. I already fixed it in the working version. But that wasn't the problem setting it to step would just make the learning rate decay faster, the problem is it was not decaying at all.

**Comment by awaelchli** [comment] 2023-09-18 12:09
If `num_warmup_steps > num_training_step` it can't decay! This is likely the case if you accidentally set num_training_step to max_epochs (and max_epochs is a small number). What are these values in your case?

**Comment by ririya** [comment] 2023-09-18 15:42
Just to confirm setting the interval to “epochs” is another option right? Like I mentioned, I was seeing the problem with every single scheduler, nothing to do with the warm up. I really think there’s a big problem here

**Comment by ririya** [comment] 2023-09-18 15:46
One more thing I was trying to run the lr finder and ran into the same problem. The finder was running 100 steps with the same learning rate. As the finder also uses a scheduler, I assume it’s the same problem. Once I fixed the plmodule the lr finder also started working. I’m not sure exactly what’s the problem, but I was thinking it could be something with the imports.

**Comment by awaelchli** [comment] 2023-09-18 23:37
Ok thanks. I'm closing the issue since there is no clear indication what is not working. If you ever come back to it, or someone else finds and issue that we can reproduce, we can reopen the investigation.

**Closed by awaelchli** 2023-09-18 23:37 UTC
Labels: bug, waiting on author, optimization, ver: 2.0.x
