### ISSUE TITLE
GPU memory consumption fluctuates rapidly with FSDP training

### ISSUE THREAD

**Issue by manideep2510** [Lightning-AI/lightning#13766] opened 2022-07-20 17:04 UTC
### Discussed in https://github.com/Lightning-AI/lightning/discussions/13594

<div type='discussions-op-text'>

<sup>Originally posted by **manideep2510** July 11, 2022</sup>
Hi, I'm trying to use FSDP training with Pytorch Lightning for a classification training task which has 1 Million classes in the classification layer, and the layer before that has 512 nodes. Without FSDP, I could not fit the model into 4 GPUs as expected, because there are around 512 Million parameters in the last layer. With FSDP, after model sharding of the last layer, I was able to fit the model and train it as well on these 4 GPUs. 

But, with FSDP, the GPU memory consumption fluctuates rapidly between 6.5GB and 10GB. Because of this, I am not able to increase the batch size. Is this behavior expected, or is this a bug in Fairscale/Lightning, or am I using FSDP wrong? Any help will be appreciated.

System & Environment
4 x RTX 2080Ti, CUDA 11.6
12 Core Intel Xeon
RAM 64GB installed
Torch 1.12.0
Pytorch-lightning 1.6.4
fairscale 0.4.6
Python 3.9.13

### Memory Consumption

https://user-images.githubusercontent.com/25865501/178203382-58cdd4b0-190b-4c1f-9051-86364260ced9.mov

The part of Lightning Module where the Linear layer is wrapped with FSDP's `wrap()`,
```python
class Model(pl.LightningModule):
    def __init__(self, embedding_size=512, num_classes=1000000, config, mode='classify'):
        super(Model, self).__init__()
        self.mode = mode  # 'classify' or 'encode' or 'both'
        self.num_classes = num_classes
        self.embedding_size = embedding_size
        
        self.backbone = SEBackBone(embedding_size=embedding_size)
        self.classifier = nn.Linear(embedding_size, num_classes, bias=False)

        self.arcloss = ArcLoss()
        self.criterion = nn.CrossEntropyLoss()
        self.metric = torchmetrics.Accuracy()

        self.config = config
        self.lr = config.lr
        self.momentum = config.momentum
        self.weight_decay = config.weight_decay 
    def configure_sharded_model(self):
        # Wrap the last layer with 1 Million nodes for sharding
        self.classifier = wrap(self.classifier)
    
    def forward(self, x, mode=None):
        features = self.backbone(x)
        output = self.classifier(features)
        return output
```

</div>

cc @borda @awaelchli @carmocca

**Comment by w2ex** [comment] 2023-02-02 14:51
Hi,
I have this same issue with `fsdp_native` under 1.9.0. This does not happen with `fsdp` (fairscale), but since it is gonna be deprecated I'll have to change... Is this a known issue ? Could someone find a fix for this yet ?
This is also an issue since I have to divide my batch size by 10  switching from `fsdp` to `fsdp_native` and I'd like being able to keep things consistant.

**Comment by carmocca** [comment] 2023-02-02 17:32
Can you share your `Trainer(...)` arguments?

**Comment by w2ex** [comment] 2023-02-03 08:45
My Trainer looks like this :
```
trainer = pl.Trainer(
        logger=[logger, logger_tensorboard],
        default_root_dir=experiment_folder,
        callbacks=callbacks, #learning rate monitor and model checkpointing callbacks
        val_check_interval=args.val_steps * args.batch_acc / len(train_dataloader),
        log_every_n_steps=args.val_steps // torch.cuda.device_count(),
        max_epochs=args.epochs,
        accelerator="gpu",
        devices=args.gpus,
        strategy="fsdp_native",
        accumulate_grad_batches=3,
        plugins=[MixedPrecisionPlugin(16, device='cuda',
                                            scaler=GradScaler(init_scale=65536.0, growth_factor=2.0, backoff_factor=0.5,
                                                              growth_interval=2000, enabled=True))]
    )
```
The model I am training on is a Resnet based on timm implementation with a classifier head. I have not been able to make a dummy code to replicate this behaviour but I will try to today.
Note : when using `fsdp` (i.e. Fairscale), I need not overwrite `configure_sharded_model()` in my LightningModule and can use a batch size of 300. When using `fsdp_native`, I have a CUDA out of memory error even if the batch size is set to 1.
If I overwrite `configure_sharded_model()`, I can run it with a batch size of 30 only and it is 2 times slower than `fsdp`.

**Comment by w2ex** [comment] 2023-02-09 10:15
@carmocca the difference in memory usage is resolved by #16687, however the fluctuation of the memory usage with `fsdp_native` remains. It does not appear in the dummy code I posted though. I will try and see if I can replicate it to understand if it comes from a bad configuration of mine or from the sharding implementation.
My guess would be an uneven shard size, which would explain the fluctuation as each shard is sequentially loaded into memory for the forward and backward passes.

**Comment by awaelchli** [comment] 2023-11-02 00:48
Closing this old issue. I haven't seen this fluctuation in any of my FSDP experiments with recent versions of PyTorch. But please let me know if this still occurs today.

**Comment by awaelchli** [comment] 2023-11-02 00:49
@tshu-w If you still have the repro, I'd be willing to look into it.

**Comment by carmocca** [comment] 2023-11-02 01:29
The cause of this is likely https://dev-discuss.pytorch.org/t/fsdp-cudacachingallocator-an-outsider-newb-perspective/1486. It could be verified by profiling the code and checking if the spikes appear at the beginning of backward. If so, this would be an FSDP issue in PyTorch

**Closed** 2023-11-20 21:54 UTC
Labels: bug, performance, strategy: fsdp
