### ISSUE TITLE
Conda installation defaults to using a very old version (0.8.5) instead of latest version (1.7)

### ISSUE THREAD

**Issue by TheShadow29** [Lightning-AI/lightning#14374] opened 2022-08-23 22:59 UTC
## 🐛 Bug

On a new environment, doing the conda installation results in installing "conda-forge/noarch::pytorch-lightning-0.8.5-py_0". 

### To Reproduce

```
conda create -n test_env python=3.9
conda install ipython jupyter
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
conda install pytorch-lightning -c conda-forge
```

### Expected behavior

It should install latest version when possible.

### Environment

- PyTorch Version (e.g., 1.10): 1.12
- Python version (e.g., 3.9): 3.9
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.6
- GPU models and configuration: 3090
- How you installed PyTorch (`conda`, `pip`, source): conda

**Comment by awaelchli** [comment] 2022-08-24 15:03
I was able to reproduce it. It is enough to do:

```
conda create -n test_env python=3.9
conda install pytorch-lightning -c conda-forge
```

@Borda do you know what could be the reason for this? The latest version is correctly hosted [here](https://anaconda.org/conda-forge/pytorch-lightning).

**Comment by Borda** [comment] 2022-08-24 22:25
> do you know what could be the reason for this? The latest version is correctly hosted [here](https://anaconda.org/conda-forge/pytorch-lightning).

not sure, but it sounds strange that would take a version so old... :(
also I think that back then when 0.8.5 was released py 3.9 was not out yet :rabbit:

**Comment by maxencewynen** [comment] 2022-09-09 08:48
Hi @Borda , do you have any updates on this issue? I have the exact same issue, and trying in a fresh conda environment - like [this link](https://stackoverflow.com/questions/73084185/conda-is-installing-a-very-old-version-of-pytorch-lightning) suggests  - does not resolve it.

**Comment by Borda** [comment] 2022-09-19 06:23
ok, let me add CI for installing on conda... :rabbit:

**Comment by otaj** [comment] 2022-09-19 14:44
Hi everyone, what `conda` version are you using? I just downloaded `conda` 4.14.0 and cannot reproduce on Linux

**Comment by awaelchli** [comment] 2022-09-19 15:05
My conda version was conda 4.12.0 (still is) and I'm on MacOS

**Comment by otaj** [comment] 2022-09-21 13:37
I am running in circles while trying to reproduce this and was just not able to. Only thing that is remotely notable about `pytorch-lightning 0.8.5` is the fact that it is the last version allowing `tensorboard<2`.

Could please all of you who are able to reproduce this behavior (@awaelchli, @maxencewynen, @TheShadow29) post here:
* Series of commands leading to creating such environment, ideally as minimal as possible.
* `conda list` of the resulting environment.
* `conda conda list -n base`
* your OS and ideally also method of obtaining conda as it seems different distributions differ in some default options.

Thank you!

**Comment by otaj** [comment] 2022-09-21 13:45
There's one more notable difference between `pytorch-lightning=0.8.5` and any newer version - `pytorch-lightning=0.8.5` has a lower bound version pin on `future>=0.17.1`, whereas newer versions require `future` without any pin all the way to `1.7.2` and from `1.7.3` we don't require `future` at all. Could it be it? At the time of reporting this issue, `1.7.2` was the latest version published on `conda-forge` and `1.7.3` wasn't released out yet.

**Comment by awaelchli** [comment] 2022-09-21 21:11
> Series of commands leading to creating such environment, ideally as minimal as possible.

I initially reproduced using https://github.com/Lightning-AI/lightning/issues/14374#issuecomment-1225849005
But now, spookingly, I CANNOT anymore. How is it possible. Still same conda version 4.12 (miniconda). And I didn't change anything since last time.

**Comment by TheShadow29** [comment] 2022-09-22 04:56
I can confirm as well. It now uses 1.7.6. I am not sure what changed though. My conda env is same as it was last time. My guess is some dependency somewhere was removed but I am not sure.

**Comment by otaj** [comment] 2022-09-22 06:54
It might have been `future`, as I said, this dependency was dropped between `1.7.2` and `1.7.3` (at least on `conda-forge` side). Both of you reported at the time when latest version out was `1.7.2`. It could be the fact that it had hard time finding some.

Let's wait on @maxencewynen and if he reports no issue anymore, I will close this. If he's able to still reproduce, I will investigate further (although I don't know where to anymore :joy:)

**Comment by otaj** [comment] 2022-09-22 07:16
It is possible _something_ was broken and got fixed by this PR https://github.com/conda-forge/pytorch-lightning-feedstock/pull/97

**Comment by awaelchli** [comment] 2022-09-27 09:29
@maxencewynen Has this been resolved for you as well? Would you mind checking that it downloads the latest version now? Thanks!

**Comment by maxencewynen** [comment] 2022-09-29 14:38
Sorry for the late reply. The issue has been resolved for me as well!

**Comment by otaj** [comment] 2022-09-29 15:09
Awesome! :rocket: Closing this issue then

**Closed by otaj** 2022-09-29 15:09 UTC
Labels: bug, priority: 0, 3rd party, pl

**Comment by Aroksak** [comment] 2022-10-31 16:11
Faced this today with latest conda (22.9.0). Resolved only with specifying pytorch-lightning==1.7.7.
For some reasons when installing pl 1.7.7 conda also downgraded openssl from 3.0.5 all the way down to 1.1.1, could it be connected?
Minimal steps to reproduce (or not?):

**Comment by iceboundflame** [comment] 2022-11-25 04:25
Also observed this happening (`conda install pytorch-lightning -c conda-forge` installed pytorch-lightning 0.8.5 and openssl 1.1.1).
