### ISSUE TITLE
Allow for setting distributed timeout for cases where there are long data preprocessing times.

### ISSUE THREAD

**Issue by ChickenTarm** [Lightning-AI/lightning#12936] opened 2022-04-29 23:32 UTC
## 🚀 Feature

Allow for setting the torch.distributed timeout to your own custom timing. Currently it is at 30 minutes, but there are some cases where each node in distributed training have very long preprocessing times of the data that exceed 30 minutes. In my case I need to manually preprocess the data per node before launching a distributed job else it will timeout. Initially the processing was done after launching the distributed job, but once I acquired more data and have more complicated data processing pipelines, it went passed 30 minutes which would crash the job until it hit the max number of restarts.

**Comment by ChickenTarm** [comment] 2022-06-13 15:33
Is this something that can't really be done easily since this isn't exposed by torchrun?

**Comment by carmocca** [comment] 2022-07-11 21:21
I believe this is a duplicate of https://github.com/Lightning-AI/lightning/issues/13211. Which was implemented and will be available in PL 1.7

**Closed by carmocca** 2022-07-11 21:21 UTC
Labels: needs triage
