### ISSUE TITLE
Bug with add_subclass_arguments() or ParamData() (or smth else?)

### ISSUE THREAD

**Issue by usernameisntavailableble** [Lightning-AI/lightning#18546] opened 2023-09-13 15:08 UTC
### Bug description
---------------------update below---------------------------
Tentatively I ran this:

```
python main.py fit --config config.yml
```
 
as you may curious about the main.py
```

if __name__ == "__main__":cli = LightningCLI(
        model_class=SketchDiffusion,
        datamodule_class=GenericDM,
        trainer_defaults={
            "callbacks": [
                LearningRateMonitor(logging_interval="step"),
                ModelCheckpoint(monitor="valid/loss", filename="model", save_last=True),
                TQDMProgressBar(refresh_rate=1 if sys.stdin.isatty() else 0),
            ]
        },
        parser_kwargs={"parser_mode": "omegaconf"},
        subclass_mode_data=True,
        run=True,
    )
```

Yet this showed up

```
File "SOMEDIRECTORY\main.py", line SOMENUMBER, in <module>
    cli = LightningCLI(
          ^^^^^^^^^^^^^
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 515, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 551, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 624, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 632, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 594, in _add_arguments
    parser.add_lr_scheduler_args(LR_SCHEDULER_REGISTRY.classes)
  File "SOMEPATH\Lib\site-packages\pytorch_lightning\utilities\cli.py", line 213, in add_lr_scheduler_args
    self.add_subclass_arguments(lr_scheduler_class, nested_key, **kwargs)
  File "SOMEPATH\Lib\site-packages\jsonargparse\_signatures.py", line 507, in add_subclass_arguments
    param = ParamData(name=nested_key, annotation=Union[baseclass], component=baseclass)
                                                  ~~~~~^^^^^^^^^^^
  File "SOMEPATH\Lib\typing.py", line 355, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "SOMEPATH\Lib\typing.py", line 478, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "SOMEPATH\Lib\typing.py", line 685, in Union
    raise TypeError("Cannot take a Union of no types.")
TypeError: Cannot take a Union of no types.

```
We guess something is off with add_subclass_arguments() or ParamData(), but not sure.

We tried on both mac and windows, both pythong 3.9 or 3.11. But nothing promissing happened.

----------------------updated Sep14---------------------------

I was trying to train the model from [https://github.com/dasayan05/chirodiff](url), where the model and datamodule seperately are SketchDiffusion and GenericDM. I hope it's not too big to be helpful.

### What version are you seeing the problem on?

master

### More info

Thanks a lot!!

cc @carmocca @mauvilsa

**Comment by awaelchli** [comment] 2023-09-13 15:45
@usernameisntavailableble I think to understand your issue, we probably need to look at the parameter definitions of your model/datamodule. Could you please post a code snippet that can reproduce it?

**Comment by usernameisntavailableble** [comment] 2023-09-14 08:22
Hey! 

The version of lightning is 1.5.9; and jsonargparse is 4.24.1. I also updated the bug description:).

**Comment by awaelchli** [comment] 2023-09-14 10:13
Can you try installing `pip install jsonargparse==4.1.4` which was the version published alongside pytorch-lightning 1.5.9?

**Comment by usernameisntavailableble** [comment] 2023-09-14 11:21
I just tried. Unfortunately still the same error..

**Comment by mauvilsa** [comment] 2023-09-14 12:20
That error message can be reproduced like:
```python
>>> from typing import Union
>>> Union[tuple()]
...
TypeError: Cannot take a Union of no types.
```

I guess this just means that `LR_SCHEDULER_REGISTRY.classes` is empty. I did not implement these registers, so not really sure how it was supposed to work. They don't exist anymore, so it wouldn't be a problem with a recent version of lightning.

**Comment by usernameisntavailableble** [comment] 2023-09-14 13:21
Also just updated lightning to the newest version, and no same error message came out!

Thanks a lot!

**Comment by awaelchli** [comment] 2023-09-14 17:36
Glad this worked for you now. Thanks @mauvilsa for the help. 
I'm closing it now since it appeared in an old lightning version. Let us know if you see more issues.

**Closed by awaelchli** 2023-09-14 17:36 UTC
Labels: bug, lightningcli
