### ISSUE TITLE
Loading the `state_dict` of a model throws a `ReferenceError`

### ISSUE THREAD

**Issue by stwerner97** [Lightning-AI/lightning#12233] opened 2022-03-04 19:37 UTC
## 🐛 Bug

The `state_dict()` methods throws an `ReferenceError: weakly-referenced object no longer exists` error if several `pl.LightningModule` objects are stored in a list and the `enable_model_summary` parameter of the `Trainer` class is set to `True`.

### To Reproduce
The code below is adapted from the [Bug Report Model](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.py) and reproduces the issue when `enable_model_summary=True`, but works if `enable_model_summary=False`.
````python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

class Ensemble:
    def __init__(self):
        self.models = [BoringModel() for _ in range(5)]

    def fit(self, data):
        for model in self.models:
                        
            trainer = Trainer(max_epochs=1, enable_model_summary=True)
            trainer.fit(model, data)

def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    ensemble = Ensemble()
    ensemble.fit(train_data)

    for model in ensemble.models:
        print(model.state_dict())


if __name__ == "__main__":
    run()
   
````

### Expected behavior

The `state_dict` method should not throw an `ReferenceError: weakly-referenced object no longer exists` error.

### Environment
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.20.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2+cpu
        - pytorch-lightning: 1.5.10
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.8.10
        - version:           1.5.10

cc @tchaton @kaushikb11 @awaelchli @rohitgr7

**Comment by stwerner97** [comment] 2022-03-04 19:56
The error actually seems unrelated to `enable_model_summary`.  Although `enable_model_summary = False` resolves the issue in the minimal example above, it does not work for my original code.

**Comment by ananthsub** [comment] 2022-03-04 19:58
Do you see the issue if you print the model's state_dict inside the loop? or only outside the loop? the trainer is likely garbage collected since it's lifetime is only within the loop.

**Comment by stwerner97** [comment] 2022-03-04 20:12
Only outside the loop. If I store references to the `Trainer` objects to extend their lifetime, the issue is resolved. So garbage collection seems indeed to be the issue.

**Comment by davidegraff** [comment] 2022-04-19 16:55
was this fixed with #12785 ? I'm having issues where a call to `.state_dict()` produces this same `ReferenceError` and don't know how to avoid it beyond wrapping in a `try/except`

**Comment by awaelchli** [comment] 2022-04-24 23:02
Hey @davidegraff 
No, I tried to fix it in that PR without success unfortunately. 

The error is caused because
1. LightningModule registers state_dict hooks at initialzation
2. The trainer attribute on the LM is a proxy to a weak reference
3. When calling state_dict in your script, the state_dict hooks are called and iterate over `model.__dict__`
4. When hitting the trainer attribute inside the `model.__dict__` iteration, a reference error occurs because by the time we reach this attribute, the garbage collector has already removed the object. 

This error wouldn't occur if the trainer wasn't a weak reference, or if the state dict hooks weren't running. 

In my PR, I tried hacking it by checking if trainer has any weak references left and convert it to None, but that didn't work as other issues started to occur.

**Comment by carmocca** [comment] 2022-07-28 19:49
@awaelchli Is this blocked by coming up with a solution?

**Comment by awaelchli** [comment] 2022-08-02 10:36
Yes, nothing I tried worked. It is hard to get this right due to the weak references and garbage collection.

**Comment by carmocca** [comment] 2022-08-03 12:37
The repro in the top post doesn't produce the error anymore. Perhaps this is not an issue worth exploring anymore.

Otherwise, as a workaround, couldn't we ignore the `Trainer` state instead of raising an exception?

**Comment by awaelchli** [comment] 2022-08-03 20:08
I can still reproduce it on commits before 800cf0b3ffb1b8dc94673cf5abe8e91703a59cd7, torch 1.12, Python 3.10. Weirdly enough not on the latest commits on master. I can't explain it, there must be some non-determinism involved here.

**Comment by awaelchli** [comment] 2022-11-21 08:54
I ran the script in a loop again 50 times and it didn't show the reference error. Let us know if the issue occurs again on Lightning >= 1.8.0.

**Closed by awaelchli** 2022-11-21 08:54 UTC
Labels: bug, won't fix, priority: 2
